### ISSUE TITLE
More than 20 participants can schedule more than 20 dependencies

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#100]
Hello, 

I am attempting to run freesurfer on several datasets, and I keep receiving notification that my analysis has been 'rejected'. Please see screenshot for an example. 

I am using v21, and typing the random string '12345' into the license key field. 

Please advise. I would like be able to run freesurfer on all uploaded datasets. 

Thanks!

<img width="479" alt="screen shot 2017-09-23 at 3 17 22 pm" src="https://user-images.githubusercontent.com/26071772/30777582-5d7776e0-a072-11e7-9ac6-36738bfc70db.png">

**Comment by nellh** [comment]
This is a bug in the logic for breaking jobs up into groups of 20 tasks per level.

``` 
server_1  | { ClientException: Error executing request, Exception : Job cannot have more than 20 dependencies, RequestId: 3d3eabd9-a15c-11e7-b66f-2f2dbe98c126
server_1  |     at Object.extractError (/srv/crn-server/node_modules/aws-sdk/lib/protocol/json.js:48:27)
server_1  |     at Request.extractError (/srv/crn-server/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
server_1  |     at Request.callListeners (/srv/crn-server/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
server_1  |     at Request.emit (/srv/crn-server/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
server_1  |     at Request.emit (/srv/crn-server/node_modules/aws-sdk/lib/request.js:678:14)
server_1  |     at Request.transition (/srv/crn-server/node_modules/aws-sdk/lib/request.js:22:10)
server_1  |     at AcceptorStateMachine.runTo (/srv/crn-server/node_modules/aws-sdk/lib/state_machine.js:14:12)
server_1  |     at /srv/crn-server/node_modules/aws-sdk/lib/state_machine.js:26:10
server_1  |     at Request.<anonymous> (/srv/crn-server/node_modules/aws-sdk/lib/request.js:38:9)
server_1  |     at Request.<anonymous> (/srv/crn-server/node_modules/aws-sdk/lib/request.js:680:12)
server_1  |     at Request.callListeners (/srv/crn-server/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
server_1  |     at Request.emit (/srv/crn-server/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
server_1  |     at Request.emit (/srv/crn-server/node_modules/aws-sdk/lib/request.js:678:14)
server_1  |     at Request.transition (/srv/crn-server/node_modules/aws-sdk/lib/request.js:22:10)
server_1  |     at AcceptorStateMachine.runTo (/srv/crn-server/node_modules/aws-sdk/lib/state_machine.js:14:12)
server_1  |     at /srv/crn-server/node_modules/aws-sdk/lib/state_machine.js:26:10
server_1  |   message: 'Error executing request, Exception : Job cannot have more than 20 dependencies, RequestId: 3d3eabd9-a15c-11e7-b66f-2f2dbe98c126',
server_1  |   code: 'ClientException',
server_1  |   time: 2017-09-24T19:11:59.509Z,
server_1  |   requestId: '3d3eabd9-a15c-11e7-b66f-2f2dbe98c126',
server_1  |   statusCode: 400,
server_1  |   retryable: false,
server_1  |   retryDelay: 27.16978709572242 }
```

**Comment by nellh** [comment]
I've narrowed this down and reproduced it with a test. The issue is that jobs with 3 levels have their dependencies erroneously passed to later analysis levels (participant (0) -> group1 (20) -> group2 (21)) and this exceeds the Batch limit of 20.
