### ISSUE TITLE
TypeError: Cannot read property 'email' of null

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1006]
https://sentry.io/openneuro/openneuro/issues/764760913/

```
TypeError: Cannot read property 'email' of null
  at _comment (./scripts/common/partials/comment-tree.jsx:287:39)
  at render (./scripts/common/partials/comment-tree.jsx:341:15)
...
(7 additional frame(s) were not displayed)
```

**Comment by nellh** [comment]
This was a bug in an old version of the this component.
