### ISSUE TITLE
openneuro-cli: TypeError: Cannot set property 'files' of undefined

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1012]
```
> openneuro upload bids/
? This will create a new dataset, continue? (Y/n) (node:20759) ExperimentalWarning: The http2 module is an experimental API.
? This will create a new dataset, continue? Yes
(node:20759) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'files' of undefined
    at Object.format (/usr/lib/node_modules/openneuro-cli/node_modules/bids-validator/utils/issues/index.js:74:39)
    at NIFTI.validate.then.niftiIssues (/usr/lib/node_modules/openneuro-cli/node_modules/bids-validator/validators/bids/fullTest.js:183:49)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:20759) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20759) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

Reported by a user - could not replicate locally.

**Comment by nellh** [comment]
The error handling around this has been improved and this shouldn't be an issue now.
