### ISSUE TITLE
Error: Network error: request to https://openneuro.org/crn/graphql failed, reason: socket hang up

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#1015]
I am getting a weird behavior when using the openneuro-cli.

When I start uploading:
```
[chrisgor@sh-101-58 ~]$ singularity run -B /oak:/oak /share/PI/russpold/singularity_images/node-11.4.0.simg /home/users/chrisgor/openneuro-cli/node_modules/.bin/openneuro upload -d ds001615 --ignoreWarnings /oak/stanford/groups/russpold/data/NARPS/ ds001205/
Adding files to "ds001615"
Skipping existing file - "CHANGES"
Skipping existing file - "T1w.json"
Skipping existing file - "dataset_description.json"
Skipping existing file - "participants.tsv"
Skipping existing file - "task-MGT_bold.json"
Skipping existing file - "task-MGT_sbref.json"
Skipping existing file - "derivatives/check_mriqc.py"
Transferring "derivatives/group_T1w.html" - 13% complete (417.8 KB remaining)
(node:44529) UnhandledPromiseRejectionWarning: Error: Network error: request to https://openneuro.org/crn/graphql failed, reason: socket hang up
    at new ApolloError (/home/users/chrisgor/openneuro-cli/node_modules/apollo-client/bundle.umd.js:85:32)
    at Object.error (/home/users/chrisgor/openneuro-cli/node_modules/apollo-client/bundle.umd.js:918:32)
    at notifySubscription (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at notifySubscription (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at linkFetch.then.then.then.catch.error (/home/users/chrisgor/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:130:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:44529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:44529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Transferring "derivatives/group_T1w.html" - 100% complete
Transferring "derivatives/group_T1w.tsv" - 100% complete
Transferring "derivatives/group_bold.html" - 100% complete
Transferring "derivatives/group_bold.tsv" - 100% complete
Transferring "derivatives/sub-001_T1w.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-01_bold.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-02_bold.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-03_bold.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-04_bold.html" - 100% complete
Transferring "derivatives/sub-002_T1w.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-01_bold.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-02_bold.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-03_bold.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-04_bold.html" - 100% complete
Transferring "derivatives/sub-003_T1w.html" - 100% complete
Transferring "derivatives/sub-003_task-MGT_run-01_bold.html" - 100% complete
Transferring "derivatives/sub-003_task-MGT_run-02_bold.html" - 100% complete
Transferring "derivatives/sub-003_task-MGT_run-03_bold.html" - 100% complete
Transferring "derivatives/sub-003_task-MGT_run-04_bold.html" - 100% complete              
```
I interrupt the process with Ctrl-C. Then I try to resume it again:

```
[chrisgor@sh-101-58 ~]$ singularity run -B /oak:/oak /share/PI/russpold/singularity_images/node-11.4.0.simg /home/users/chrisgor/openneuro-cli/node_modules/.bin/openneuro upload -d ds001615 --ignoreWarnings /oak/stanford/groups/russpold/data/NARPS/ ds001205/
Adding files to "ds001615"
Skipping existing file - "T1w.json"
Skipping existing file - "dataset_description.json"
Skipping existing file - "participants.tsv"
Skipping existing file - "task-MGT_bold.json"
Skipping existing file - "task-MGT_sbref.json"
Skipping existing file - "derivatives/check_mriqc.py"
Transferring "CHANGES" - 100% complete
Transferring "derivatives/group_T1w.html" - 13% complete (417.8 KB remaining)
(node:44996) UnhandledPromiseRejectionWarning: Error: Network error: request to https://openneuro.org/crn/graphql failed, reason: socket hang up
    at new ApolloError (/home/users/chrisgor/openneuro-cli/node_modules/apollo-client/bundle.umd.js:85:32)
    at Object.error (/home/users/chrisgor/openneuro-cli/node_modules/apollo-client/bundle.umd.js:918:32)
    at notifySubscription (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at notifySubscription (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at linkFetch.then.then.then.catch.error (/home/users/chrisgor/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:130:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:44996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:44996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Transferring "derivatives/group_T1w.html" - 100% complete
Transferring "derivatives/group_T1w.tsv" - 100% complete
Transferring "derivatives/group_bold.html" - 100% complete
Transferring "derivatives/group_bold.tsv" - 100% complete
Transferring "derivatives/sub-001_T1w.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-01_bold.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-02_bold.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-03_bold.html" - 100% complete
Transferring "derivatives/sub-001_task-MGT_run-04_bold.html" - 100% complete
Transferring "derivatives/sub-002_T1w.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-01_bold.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-02_bold.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-03_bold.html" - 100% complete
Transferring "derivatives/sub-002_task-MGT_run-04_bold.html" - 100% complete
Transferring "derivatives/sub-003_T1w.html" - 100% complete
Transferring "derivatives/sub-003_task-MGT_run-01_bold.html" - 100% complete
```

Two weird issues:
1. The network error happens at the same file - always.
2. Files that were previously transferred (like `derivatives/group_T1w.tsv`) were transferred again as if they were not found on the server.

I'm using node 11.4.0

**Comment by nellh** [comment]
This is what's logged on the server side:

```
web_1      | 2018/12/11 20:03:01 [warn] 7#7: *9268023 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/0/66/0000028660 while reading upstream, client: ..., server: , request: "POST /crn/graphql HTTP/2.0", upstream: "http://172.19.0.41:8111/crn/graphql", host: "openneuro.org", referrer: "https://openneuro.org/datasets/ds001615"
server_1   | Client disconnected during upload for dataset "ds001615".
```

Looks like nginx buffers this and Express gives up waiting on the nginx socket.

**Comment by chrisgorgo** [comment]
Is data being actually transferred after the initial socket hang up?

**Comment by nellh** [comment]
Yeah, to the nginx buffer but not to the NodeJS backend.

**Comment by chrisgorgo** [comment]
Ok. So to clarify until this is fixed it does not make sense to ignore the initial error and carry on transferring?

**Comment by chrisgorgo** [comment]
BTW I tried with node 10.14.1 and I am getting very similar results

```
[chrisgor@sh-ln02 login ~]$ singularity run -B /oak:/oak /share/PI/russpold/singularity_images/node-10.14.1.simg /home/users/chrisgor/openneuro-cli/node_modules/.bin/openneuro upload --ignoreWarnings /oak/stanford/groups/russpold/data/NARPS/ds00120 5/
? This will create a new dataset, continue? Yes
"ds001616" created with label "ds001205"
Transferring "CHANGES" - 100% complete
Transferring "T1w.json" - 100% complete
Transferring "dataset_description.json" - 100% complete
Transferring "participants.tsv" - 100% complete
Transferring "task-MGT_bold.json" - 100% complete
Transferring "task-MGT_sbref.json" - 100% complete
Transferring "derivatives/check_mriqc.py" - 100% complete
Transferring "derivatives/group_T1w.html" - 13% complete (417.8 KB remaining)
(node:2686) UnhandledPromiseRejectionWarning: Error: Network error: request to https://openneuro.org/crn/graphql failed, reason: getaddrinfo EMFILE openneuro.org openneuro.org:443
    at new ApolloError (/home/users/chrisgor/openneuro-cli/node_modules/apollo-client/bundle.umd.js:85:32)
    at Object.error (/home/users/chrisgor/openneuro-cli/node_modules/apollo-client/bundle.umd.js:918:32)
    at notifySubscription (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at notifySubscription (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/home/users/chrisgor/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at linkFetch.then.then.then.catch.error (/home/users/chrisgor/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:130:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2686) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The error is slightly different and the CLI exists after it instead of continuing to upload. This looks very similar to the issues I have seen on Windows (https://github.com/OpenNeuroOrg/openneuro/issues/646) even though this time it's a linux system.

**Comment by chrisgorgo** [comment]
I've rebuild the container ground up with 10.14.1 (this time installing openneruo-cli in the container) and it seems to work now.

**Comment by chrisgorgo** [comment]
The issue is still happening - just later during the transfer.

**Comment by nellh** [comment]
This should be further improved with today's release.
