### ISSUE TITLE
Add error message for CLI TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1107]
reported by user - could not replicate this error locally
dataset: 1769

This dataset is also not present on the openneuro github repo so limits options to download. Locally I was able to download dataset via the Node.js client.

```$> node_modules/.bin/openneuro download --snapshot 1.1.0 ds001769 ds001769-download/

/home/usr/proj/openneuro/node_modules/openneuro-cli/src/config.js:1
TypeError: path must be a string or Buffer
at Object.fs.openSync (fs.js:646:18)
at Proxy.fs.readFileSync (fs.js:551:33)
at readConfig (/home/usr/proj/openneuro/node_modules/openneuro-cli/src/config.js:14:13)
at getUrl (/home/usr/proj/openneuro/node_modules/openneuro-cli/src/config.js:45:29)
at getDownloadMetadata (/home/usr/proj/openneuro/node_modules/openneuro-cli/src/download.js:41:22)
at getDownload (/home/usr/proj/openneuro/node_modules/openneuro-cli/src/download.js:56:3)
at Command.download (/home/usr/proj/openneuro/node_modules/openneuro-cli/src/actions.js:145:5)
at Proxy.listener (/home/usr/proj/openneuro/node_modules/commander/index.js:315:8)
at emitTwo (events.js:126:13)
at Proxy.emit (events.js:214:7)```

**Comment by danieltomasz** [comment]
I am getting the same error


```
➜ openneuro download --snapshot 1.0.3 ds000117 ds000117-download/
/home/daniel/.config/yarn/global/node_modules/openneuro-cli/src/config.js:1
TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at readConfig (/home/daniel/.config/yarn/global/node_modules/openneuro-cli/src/config.js:14:13)
    at getUrl (/home/daniel/.config/yarn/global/node_modules/openneuro-cli/src/config.js:45:29)
    at getDownloadMetadata (/home/daniel/.config/yarn/global/node_modules/openneuro-cli/src/download.js:41:22)
    at getDownload (/home/daniel/.config/yarn/global/node_modules/openneuro-cli/src/download.js:56:3)
    at Command.download (/home/daniel/.config/yarn/global/node_modules/openneuro-cli/src/actions.js:145:5)
    at Proxy.listener (/home/daniel/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Proxy.emit (events.js:214:7)
```

**Comment by nellh** [comment]
@danieltomasz This is a failure to read the ~/.openneuro configuration file. Does the file exist? You can create it with `openneuro login`. Even for public downloads, you do need to authenticate with an API key at the moment. You can obtain an API key at https://openneuro.org/keygen

**Comment by danieltomasz** [comment]
thanks for info! Maybe it would be beneficial to other new users to add this information to readme file? Or point to the documentation if this info is written somewhere else?

**Comment by nellh** [comment]
I don't think it is documented, adding it to the README is a good idea. We should also catch this unhelpful error message and offer a better explanation.
