### ISSUE TITLE
[CLI] upload error

### ISSUE THREAD

**Issue by mgxd** [OpenNeuroOrg/openneuro#1163]
Hi,

I'm attempting to upload a dataset with many derivatives - things have proceeded nicely until some of the dataset's derivatives are reached. I have run into this error a few times now (on my initial run + subsequent resume runs)

```
(node:35099) UnhandledPromiseRejectionWarning: Error: GraphQL error: getaddrinfo EAI_AGAIN datalad datalad:9877
    at new ApolloError (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:63:32)
    at Object.next (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:996:57)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.next (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:219:7)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:858:79
    at Set.forEach (<anonymous>)
    at Object.next (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:858:31)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
(node:35099) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35099) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Even though the upload has not finished, the cli exits with a return code of 0. I'm using `openneuro-cli 3.1.2`, and the dataset accession number is ds001947.

Is there a way to specify directories to avoid while uploading?

**Comment by nellh** [comment]
How large is the total upload and how many files? We do have some limitations around total file count which some derivative heavy datasets have reached.

There is not currently a way to specify directories to skip during an upload but any files which were successfully uploaded should be skipped on subsequent uploads if you specify the accession number.

**Comment by mgxd** [comment]
@nellh about 85k files, with the total size approaching 1TB.

I should be able to move the derivatives for the time being, but it would be a nice feature to include to avoid this for larger datasets.

Thanks!
