### ISSUE TITLE
OAuth logins broken

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1165]
<img width="918" alt="Screen Shot 2019-07-03 at 16 46 46" src="https://user-images.githubusercontent.com/83442/60627183-4bf05e80-9dbb-11e9-90e5-30ed68162445.png">
Reported on both Firefox (67.0) and Chrome (75.0.3770.100) this afternoon, and confirmed on Firefox (67.0.3) and Chrome (75.0.3770.100). I'm able to log into other services with ORCID, so it looks like this is on our side.

**Comment by effigies** [comment]
Same issue with Google.

```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/srv/node_modules/passport-oauth2/lib/strategy.js:408:17)
    at /srv/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /srv/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/srv/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by nellh** [comment]
Out of memory issue killed the outbound network for docker. I restarted things and it is working again.
