### ISSUE TITLE
Network error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by sappelhoff** [OpenNeuroOrg/openneuro#1221]
While reuploading(=updating) a dataset on OpenNeuro via the CLI, I get the following error:

(might be related to https://github.com/OpenNeuroOrg/openneuro/issues/937, https://github.com/OpenNeuroOrg/openneuro/issues/843)

<pre>(node:10380) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token &lt; in JSON at position 0
    at new ApolloError (/home/stefanappelhoff/.config/yarn/global/node_modules/apollo-client/bundle.umd.js:92:26)
    at Object.error (/home/stefanappelhoff/.config/yarn/global/node_modules/apollo-client/bundle.umd.js:1323:28)
    at notifySubscription (/home/stefanappelhoff/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/stefanappelhoff/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/home/stefanappelhoff/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:224:7)
    at /home/stefanappelhoff/.config/yarn/global/node_modules/apollo-client/bundle.umd.js:1100:37
    at Set.forEach (&lt;anonymous&gt;)
    at Object.error (/home/stefanappelhoff/.config/yarn/global/node_modules/apollo-client/bundle.umd.js:1099:21)
    at notifySubscription (/home/stefanappelhoff/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/home/stefanappelhoff/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:165:3)
(node:10380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

**Can somebody help me to resolve this? The dataset in question is [ds000248](https://openneuro.org/datasets/ds000248/versions/00001)**

**Comment by jasmainak** [comment]
<s>This looks like a BIDS validator error to me. I have seen this error before with the validator. It's related to some recent PRs and it's a super cryptic message I agree. Does the dataset pass the validator for you?</s>

I have no idea what this is :)

**Comment by nellh** [comment]
Was the API key used recently generated? All API keys were expired last week when we migrated to a new hosting setup. We're working on improving the error message for this in #642

**Comment by sappelhoff** [comment]
Thanks @nellh 
with a new API key, this exited cleanly:

```
=======================================================================
Upload Complete
To publish your dataset go to https://openneuro.org/datasets/ds000248
=======================================================================

```
