### ISSUE TITLE
[CLI] upload error

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1280]
using the CLI this upload will fail at the same place (roughly 80% complete of the first nifti file Update: this is happening at the same place with the same error message for all (4) nifiti files in the set)

dataset - https://openneuro.org/datasets/ds002179/versions/1.0.0

```
(node:23070) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:59:32)
    at Object.error (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1031:52)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:224:7)
    at linkFetch.then.then.then.catch.error (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:130:24)
    at <anonymous>
(node:23070) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23070) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nellh** [comment]
To clarify, this is still missing some niftis because they could not be uploaded? Or did they work via the web uploader? Can you share the full dataset through some other means so we can narrow down the upload problem?

**Comment by franklin-feingold** [comment]
Yup! There are several niftis still missing (the larger niftis) because the upload would throw out this error. I have tried iterative uploading with no luck. The web uploader didn't work either. 

I can put onto a google drive some of the larger files to ease the troubleshooting

to note: the smaller uploaded files (I was able to get some derivatives uploaded via the CLI), but this has not rendered on the user side. This was a few days ago

**Comment by nellh** [comment]
Sounds like those smaller files were written to the working tree but not committed, which makes sense if the edit did not finish due to the larger file erroring out. How big is the biggest nifti and how long approximately did it take before you saw the error?

**Comment by franklin-feingold** [comment]
Ahh I see - that is the exact case we are seeing. 

The biggest nifti is 13.81 gb with several at 13.62 gb. The upload was processing for roughly 15-20 minutes before erroring out

**Comment by ckrountree** [comment]
Note:  To date, there are five (5) nifti files that are this large (over 13gb).

**Comment by ckrountree** [comment]
Clarification from Franklin: 

> The owner has a dataset page initialized that has been shared with the journal that may be the spot to place the files to (https://openneuro.org/datasets/ds002179/versions/1.0.0).

**Comment by nellh** [comment]
This dataset is fully uploaded now, I didn't create a new snapshot but that should work as expected despite the large files (it may take a few minutes).

**Comment by franklin-feingold** [comment]
Thank you!! I will let the author know!
