### ISSUE TITLE
openneuro-cli download ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by adelavega** [OpenNeuroOrg/openneuro#1464]
openneuro download does not seem to be working on this latest version:

```
$ openneuro download --snapshot 1.0.0 ds001131 ds001131-download/

>>/home/alejandro/anaconda3/lib/node_modules/openneuro-cli/src/config.js:1
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at Object.openSync (fs.js:428:3)
    at Proxy.readFileSync (fs.js:341:35)
    at readConfig (/home/alejandro/anaconda3/lib/node_modules/openneuro-cli/src/config.js:14:13)
    at getUrl (/home/alejandro/anaconda3/lib/node_modules/openneuro-cli/src/config.js:45:29)
    at getDownloadMetadata (/home/alejandro/anaconda3/lib/node_modules/openneuro-cli/src/download.js:41:22)
    at getDownload (/home/alejandro/anaconda3/lib/node_modules/openneuro-cli/src/download.js:56:3)
    at Command.download (/home/alejandro/anaconda3/lib/node_modules/openneuro-cli/src/actions.js:204:5)
    at Proxy.listener (/home/alejandro/anaconda3/lib/node_modules/openneuro-cli/node_modules/commander/index.js:315:8)
    at Proxy.emit (events.js:182:13)
    at Proxy.EventEmitter.emit (domain.js:442:20)

```

```
$ node --version
v10.13.0

$ openneuro --version
3.9.0
```

**Comment by rwblair** [comment]
I ran into the same issue with node 12.13.1 and same version of the cli.

**Comment by nellh** [comment]
Might be a platform specific bug? It's working for me on Node 12.14.0 and Linux.

**Comment by ckrountree** [comment]
Could not reproduce.
