### ISSUE TITLE
OpenNeuro cli error - TypeError: Promise constructor's argument is not a function

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1591]
A user has hit this error when using these packages:

openneuro-cli@3.13.2
node version = v13.12.0

The user had installed node on a clean install 

```
~> openneuro
/usr/local/lib/node_modules/openneuro-cli/node_modules/promise/lib/core.js:1
TypeError: Promise constructor's argument is not a function
 at new Promise (/usr/local/lib/node_modules/openneuro-cli/node_modules/promise/lib/core.js:59:11)
 at valuePromise (/usr/local/lib/node_modules/openneuro-cli/node_modules/promise/lib/es6-extensions.js:19:11)
 at Object.<anonymous> (/usr/local/lib/node_modules/openneuro-cli/node_modules/promise/lib/es6-extensions.js:11:12)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
~> node --version
v13.12.0
```

**Comment by nellh** [comment]
This looks like it could be due to conflicting node_modules. I'd suggest using a local node_modules for openneuro-cli and seeing if that solves it. That's as simple as creating a directory and putting in an empty package.json in that directory:

```shell
mkdir openneuro-cli && cd openneuro-cli
echo '{}' > package.json
yarn add openneuro-cli
yarn run openneuro ...
```

**Comment by nellh** [comment]
I can't reproduce this with a fresh install of the CLI on node 13.12.0 or 14.2.0 - I think this is a setup issue (mixed up node_modules most likely). The `/usr/local/lib/node_modules` path points to that being likely.
