### ISSUE TITLE
`createDataset` doesn't use its `label` argument.

### ISSUE THREAD

**Issue by kousu** [OpenNeuroOrg/openneuro#1679]
**Describe the bug**

`createDataset` doesn't use its `label` argument.

**To Reproduce**

1. Use the GraphQL API to create a dataset with label set to "Brainstorm Tutorial ECoG/sEEG" with this GraphQL query:

```
mutation createDataset($label: String!) {
  createDataset(label: $label) {
    id
   __typename
  }
}
```

3. Look on the dataset page for the returned datasetId: it will have "Brainstorm Tutorial ECoG/sEEG" mentioned nowhere.

4. But try

```
mutation createDataset {
  createDataset {
    id
    __typename
  }
}
```

and get an error insisting you need to pass $label.

**Expected behavior**

I expected `createDataset` to use its `label` argument to seed `dataset_description.json`'s `Name` field.

But I think I want it to lose the parameter altogether. It's just confusing.

**Screenshots**

given

```
export AUTH_TOKEN=<your-jwt>
```

Normal, successful dataset creation:

```
$ curl 'https://openneuro.org/crn/graphql' -H 'content-type: application/json' -H 'Cookie: accessToken=$AUTH_TOKEN' --data-raw '{"operationName":"createDataset","variables":{"label":"Brainstorm Tutorial ECoG/sEEG"},"query":"mutation createDataset($label: String!) {\n  createDataset(label: $label) {\n    id\n    __typename\n  }\n}\n"}'
{"data":{"createDataset":{"id":"ds002966","__typename":"Dataset"}},"extensions":{"tracing":{"version":1,"startTime":"2020-06-28T07:54:20.849Z","endTime":"2020-06-28T07:54:25.902Z","duration":5052339040,"execution":{"resolvers":[{"path":["createDataset"],"parentType":"Mutation","fieldName":"createDataset","returnType":"Dataset","startOffset":1376007,"duration":5050369912}]}},"cacheControl":{"version":1,"hints":[{"path":["createDataset"],"maxAge":0}]},"openneuro":{"version":"3.15.0-alpha.1"}}}
```

Without $label:

```
$ curl 'https://openneuro.org/crn/graphql' -H 'content-type: application/json' -H 'Cookie: accessToken=$AUTH_TOKEN' --data-raw '{"operationName":"createDataset","variables":{},"query":"mutation createDataset {\n  createDataset {\n    id\n    __typename\n  }\n}\n"}'
{"errors":[{"message":"Field \"createDataset\" argument \"label\" of type \"String!\" is required, but it was not provided.","locations":[{"line":2,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Field \"createDataset\" argument \"label\" of type \"String!\" is required, but it was not provided.","    at Object.leave (/srv/node_modules/graphql/validation/rules/ProvidedRequiredArguments.js:69:33)","    at Object.leave (/srv/node_modules/graphql/language/visitor.js:345:29)","    at Object.leave (/srv/node_modules/graphql/language/visitor.js:395:21)","    at visit (/srv/node_modules/graphql/language/visitor.js:242:26)","    at Object.validate (/srv/node_modules/graphql/validation/validate.js:73:24)","    at validate (/srv/node_modules/apollo-server-core/src/requestPipeline.ts:426:22)","    at Object.<anonymous> (/srv/node_modules/apollo-server-core/src/requestPipeline.ts:250:32)","    at Generator.next (<anonymous>)","    at fulfilled (/srv/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}}}]}
```

**Desktop (please complete the following information):**
- [x] Not applicable 

**Smartphone (please complete the following information):**
- [x] Not applicable

**Comment by nellh** [comment]
Label argument was dropped when this API was updated to include the defaced disclaimer flag.
