### ISSUE TITLE
`openneuro download` can't handle empty snapshots

### ISSUE THREAD

**Issue by kousu** [OpenNeuroOrg/openneuro#1691]
**Describe the bug**

`openneuro download` when run on an unpublished dataset that has no snapshots defined yet crashes.

**To Reproduce**
1. `openneuro upload dataset/` and accept that it will create a new dataset
1. `DATASET=<created accession number>`
2. `mkdir alt; cd alt`
3. `openneuro download $DATASET $DATASET-copy/
3. At the empty "? Choose a snapshot (Use arrow keys)" prompt, just press Enter.
4. See 
> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined

If I pass `--draft` it works fine.

**Expected behavior**
`--draft` should be included as one of the snapshot options to download, and/or an empty list of options should terminate with a helpful message.

**Screenshots**

```
$ openneuro download ds002981 ds002981
? Choose a snapshot (Use arrow keys)
(node:35187) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/home/kousu/src/neuropoly/datalad/test-julien/node_modules/inquirer/lib/prompts/list.js:116:53)
    at MapSubscriber._next (/home/kousu/src/neuropoly/datalad/test-julien/node_modules/inquirer/node_modules/rxjs/operators/map.js:79:35)
    at MapSubscriber.Subscriber.next (/home/kousu/src/neuropoly/datalad/test-julien/node_modules/inquirer/node_modules/rxjs/Subscriber.js:93:18)
    at TakeSubscriber._next (/home/kousu/src/neuropoly/datalad/test-julien/node_modules/inquirer/node_modules/rxjs/operators/take.js:82:30)
    at TakeSubscriber.Subscriber.next (/home/kousu/src/neuropoly/datalad/test-julien/node_modules/inquirer/node_modules/rxjs/Subscriber.js:93:18)
    at Interface.handler (/home/kousu/src/neuropoly/datalad/test-julien/node_modules/inquirer/node_modules/rxjs/observable/FromEventObservable.js:210:46)
    at Interface.emit (events.js:327:22)
    at Interface.EventEmitter.emit (domain.js:485:12)
    at Interface._onLine (readline.js:337:10)
    at Interface._line (readline.js:666:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Desktop (please complete the following information):**
- [x] Not applicable 

**Smartphone (please complete the following information):**
- [x] Not applicable

**Comment by nellh** [comment]
The new CLI has resolved this issue.
