### ISSUE TITLE
GraphQL error when upload dataset using the version 3.16

### ISSUE THREAD

**Issue by jane2qian** [OpenNeuroOrg/openneuro#1706]
*  GraphQL error: Cannot read property 'length' of undefined.*

It works fine on the last version. Since version 3.16 was released yesterday, the uploading keeps failed. 

Here is the report:

(node:80130) UnhandledPromiseRejectionWarning: Error: GraphQL error: Cannot read property 'length' of undefined
    at new ApolloError (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:92:26)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1588:34
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2131:19
    at Object.next (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:322:23)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:135:18)

- MacOS
- nodejs 14.5

**Comment by nellh** [comment]
Thank you for the bug report. We had some service issues with our infrastructure this morning that are now resolved and hopefully this has fixed the issue for you. Can you test now?

If you are still having this issue, you can help us debug it by running the command line with `node --trace-warnings path/to/openneuro upload ...` and pasting any extra output.

**Comment by jane2qian** [comment]
Hi, I've tried the --trace -warning command. Here is the new bug report:

(node:91412) UnhandledPromiseRejectionWarning: Error: GraphQL error: Cannot read property 'length' of undefined
    at new ApolloError (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:92:26)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1588:34
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2131:19
    at Object.next (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:322:23)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:135:18)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:91412) Error: GraphQL error: Cannot read property 'length' of undefined
    at new ApolloError (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:92:26)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1588:34
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:2131:19
    at Object.next (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:322:23)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:135:18)
(node:91412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by nellh** [comment]
Thanks, could you try setting up a new API key? You can run `openneuro login` and follow the instruction to obtain a new key.

**Comment by jane2qian** [comment]
Thanks. I retried and the same error happens.

**Comment by nellh** [comment]
A fix for this is included in 3.16.5, thank you again for your help narrowing it down. Can you verify 3.16.5 fixes the issue for you?

**Comment by nellh** [comment]
Please reopen this if you are still running into this error uploading.
