### ISSUE TITLE
[CLI] SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1719]
**Describe the bug**
A user is attempting to upload a dataset using the openneuro cli. When the user attempts to upload a new dataset the validator completes, but as the upload begins to initialize this error message is printed (below). The dataset owner has full permissions to their dataset. When calling the openneuro command with `sudo` results is the same error. 

```
SyntaxError: Unexpected identifier
    at addTypenameToDocument (/usr/lib/node_modules/openneuro-cli/node_modules/apollo-utilities/lib/bundle.cjs.js:685:30)
    at InMemoryCache.transformDocument (/usr/lib/node_modules/openneuro-cli/node_modules/apollo-cache-inmemory/lib/bundle.cjs.js:1246:61)
    at QueryManager.transform (/usr/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1655:33)
    at QueryManager.<anonymous> (/usr/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1240:31)
    at step (/usr/lib/node_modules/openneuro-cli/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/lib/node_modules/openneuro-cli/node_modules/tslib/tslib.js:122:57)
    at /usr/lib/node_modules/openneuro-cli/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/openneuro-cli/node_modules/tslib/tslib.js:111:16)
    at QueryManager.mutate (/usr/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1229:35)
"bidsdat0/" may not exist or is inaccessible
```

**To Reproduce**
1. Enter `openneuro upload -i bidsdat0/`
2. Validator completes
3. Error is printed out before the upload starts

**Expected behavior**
the upload begins

**Additional context**
_Versions:_
openneuro-cli 3.15.1
node is 12.18.2

**Comment by nellh** [comment]
@franklin-feingold This is probably resolved in openneuro-cli 3.16.5, can you have the user test with the latest release? Clearing node_modules can be a good idea too if this is a global install.

**Comment by nellh** [comment]
@franklin-feingold Any luck with this?

**Comment by franklin-feingold** [comment]
awaiting to hear back from the dataset owner - I can close this until I hear further
