### ISSUE TITLE
Dataset landing page - Error: GraphQL error: Internal Server Error

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1742]
**Describe the bug**
When navigating to these particular datasets we are seeing an `Error: GraphQL error: Internal Server Error` 

**To Reproduce**
1. Go to [ds002094](https://openneuro.org/datasets/ds002094)
2. GraphQL message pops up

**Expected behavior**
Dataset page is rendered

**Affected datasets**

- [x] ds001946
- [x] ds002087
- [x] ds002094

**Comment by nellh** [comment]
Here's the associated traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/datalad_service/common/celery.py", line 35, in dataset_task_decorator
    return func(DataladStore(annex_path), *args[1:], **kwargs)
  File "/datalad_service/tasks/files.py", line 45, in get_files
    return get_repo_files(ds, branch)
  File "/datalad_service/common/annex.py", line 218, in get_repo_files
    return get_repo_urls(dataset.path, files)
  File "/datalad_service/common/annex.py", line 182, in get_repo_urls
    url = read_rmet_file(remote, catFile)
  File "/datalad_service/common/annex.py", line 131, in read_rmet_file
    url = parse_rmet_line(remote, nextLine)
  File "/datalad_service/common/annex.py", line 110, in parse_rmet_line
    slash = '' if remote['url'][-1] == '/' else '/'
TypeError: 'NoneType' object is not subscriptable
```

**Comment by nellh** [comment]
@franklin-feingold These should be available now.

**Comment by ckrountree** [comment]
All three datasets downloaded just fine.
