### ISSUE TITLE
Validation exits with error $summaryInput got invalid value {} at summaryInput.subjectMetadata

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1862]
**Describe the bug**
This is observed with ds002685@8333509634d7ccc37424f125982ccb7be5caa8c0

**To Reproduce**
1. Modify this dataset
2. Validation will show pending forever

**Expected behavior**
Validation shouldn't fail and should probably succeed despite this missing information.

**Additional context**
```
Exception: {"errors":[{"message":"Variable \"$summaryInput\" got invalid value {} at \"summaryInput.subjectMetadata\"; Field participantId of required type String! was not provided.","locations":[{"line":1,"column":11}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Variable \"$summaryInput\" got invalid value {} at \"summaryInput.subjectMetadata\"; Field participantId of required type String! was not provided.","","GraphQL request:1:11","1 | mutation ($summaryInput: SummaryInput!) { updateSummary(summary: $summaryInput) { id } }","  |           ^","    at /srv/node_modules/graphql/execution/values.js:114:15","    at coerceInputValueImpl (/srv/node_modules/graphql/utilities/coerceInputValue.js:99:11)","    at coerceInputValueImpl (/srv/node_modules/graphql/utilities/coerceInputValue.js:78:13)","    at coerceInputValueImpl (/srv/node_modules/graphql/utilities/coerceInputValue.js:105:35)","    at coerceInputValueImpl (/srv/node_modules/graphql/utilities/coerceInputValue.js:54:14)","    at coerceInputValue (/srv/node_modules/graphql/utilities/coerceInputValue.js:37:10)","    at _loop (/srv/node_modules/graphql/execution/values.js:107:69)","    at coerceVariableValues (/srv/node_modules/graphql/execution/values.js:119:16)","    at getVariableValues (/srv/node_modules/graphql/execution/values.js:48:19)","    at buildExecutionContext (/srv/node_modules/graphql/execution/execute.js:184:61)","    at executeImpl (/srv/node_modules/graphql/execution/execute.js:89:20)","    at execute (/srv/node_modules/graphql/execution/execute.js:64:63)","    at wrappedExecuteImpl (/srv/node_modules/elastic-apm-node/lib/instrumentation/modules/graphql.js:115:20)","    at Object.wrappedExecute (/srv/node_modules/elastic-apm-node/lib/instrumentation/modules/graphql.js:128:11)","    at /srv/node_modules/apollo-server-core/dist/requestPipeline.js:239:46","    at Generator.next (<anonymous>)","    at /srv/node_modules/apollo-server-core/dist/requestPipeline.js:7:71","    at new Promise (<anonymous>)","    at __awaiter (/srv/node_modules/apollo-server-core/dist/requestPipeline.js:3:12)","    at execute (/srv/node_modules/apollo-server-core/dist/requestPipeline.js:218:20)","    at Object.<anonymous> (/srv/node_modules/apollo-server-core/dist/requestPipeline.js:156:42)","    at Generator.next (<anonymous>)","    at fulfilled (/srv/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}}}]}
```

**Comment by ckrountree** [comment]
Fixed
