### ISSUE TITLE
[CLI] Error Stream Premature close

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1884]
**Describe the bug**
The cli outputs an `ERR_STREAM_PREMATURE_CLOSE` error. The dataset owners started the uploader and at a point in the process, this error is output for each remaining file. It appears the connection is killed to the server. it is unclear why it was killed. This error was replicated by a few dataset owners with a stable connection. 

**To Reproduce**
1. Error was produced when uploading to ds003243 and ds002241
2. Dataset owners have up to date versions of node and npm. The dataset owners have found this in v3.23.0 (it didn't appear the new version would induce this error. 

**Expected behavior**
Dataset uploads

**Comment by alexlicohen** [comment]
I am also getting this error when trying to create a new data set, or update an existing one.

(I tried the suggestion to install openneuro into a separate dir from here: https://github.com/OpenNeuroOrg/openneuro/issues/1842#issuecomment-709491276 but still no luck)

Error message:
```
../software/node_modules/.bin/openneuro upload --dataset ds003363 GSP1000/
Adding files to "ds003363"
bids-validator@1.5.7

        Summary:                  Available Tasks:        Available Modalities:
        1572 Files, 7.56GB                                T1w
        1568 - Subjects
        1 - Session


	If you have any questions, please post on https://neurostars.org/tags/bids.

=======================================================================
2750 files to be uploaded with a total size of 219.6 GB
? Begin upload? Yes
=======================================================================
Starting a new upload (3eb55d62) to dataset: 'ds003363'
ds003363 [=---------------------------------------] 1% | ETA: 95945s | 38/2750
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:121:38)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/Volumes/Drobo/Research/software/node_modules/elastic-apm-node/lib/instrumentation/index.js:309:27)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at closeStream (internal/http2/core.js:1766:14)
    at ClientHttp2Stream._destroy (internal/http2/core.js:2171:7)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at internal/http2/core.js:1063:46
    at Map.forEach (<anonymous>)
    at closeSession (internal/http2/core.js:1063:19)
    at ClientHttp2Session.destroy (internal/http2/core.js:1416:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2829:13)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket._emitTLSError (_tls_wrap.js:888:10)
    at TLSWrap.onerror (_tls_wrap.js:416:11)
    at TLSWrap.callbackTrampoline (internal/async_hooks.js:129:14) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
(node:30295) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of null
    at uploadDataset (/Volumes/Drobo/Research/software/node_modules/openneuro-cli/src/actions.js:95:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, u)
(node:30295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ckrountree** [comment]
Let's handle the error case better.  We will look into this but first guess is that this is a connection issue, in which case we can try to make it more robust.
