### ISSUE TITLE
TypeError: Cannot read property 'startTransaction' of undefined

### ISSUE THREAD

**Issue by kurobaneHITOMI** [OpenNeuroOrg/openneuro#1917]
TypeError: Cannot read property 'startTransaction' of undefined
    at Command.download (/home3/hilberthitomi05/tools/openneuro/node_modules/openneuro-cli/src/actions.js:232:30)
    at Proxy.listener (/home3/hilberthitomi05/tools/openneuro/node_modules/openneuro-cli/node_modules/commander/index.js:315:8)
    at Proxy.emit (events.js:315:20)
    at Proxy.EventEmitter.emit (domain.js:467:12)
    at Proxy.Command.parseArgs (/home3/hilberthitomi05/tools/openneuro/node_modules/openneuro-cli/node_modules/commander/index.js:651:12)
    at Proxy.Command.parse (/home3/hilberthitomi05/tools/openneuro/node_modules/openneuro-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home3/hilberthitomi05/tools/openneuro/node_modules/openneuro-cli/src/cli.js:66:11)
    at Generator.next (<anonymous>)

**Comment by ckrountree** [comment]
This seems like it may be a CLI install issue.

**Comment by ckrountree** [comment]
There have been no further details or comments.  Therefore, we are closing this issue.

**Comment by cll008** [comment]
I'm running into a similar issue when running download. I installed openneuro-cli using node:14.16 on Debian 9 (in a container) as well as on Ubuntu 18.04.5. The installations had some warnings about deprecated packages but no errors. Not sure what I should try next. Thanks. 

TypeError: Cannot read property 'startTransaction' of undefined
    at Command.download (/usr/local/lib/node_modules/openneuro-cli/src/actions.js:224:30)
    at Proxy.listener (/usr/local/lib/node_modules/openneuro-cli/node_modules/commander/index.js:315:8)
    at Proxy.emit (events.js:315:20)
    at Proxy.EventEmitter.emit (domain.js:467:12)
    at Proxy.Command.parseArgs (/usr/local/lib/node_modules/openneuro-cli/node_modules/commander/index.js:651:12)
    at Proxy.Command.parse (/usr/local/lib/node_modules/openneuro-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/openneuro-cli/src/cli.js:84:11)
    at Generator.next (<anonymous>)

**Comment by effigies** [comment]
Can you verify what version of openneuro you're using?

**Comment by cll008** [comment]
openneuro-cli@3.30.0, I installed through npm.

**Comment by franklin-feingold** [comment]
this could be an odd installation issue - may you please try reinstalling npm then openneuro-cli?

Regarding downloading, the [aws-cli](https://aws.amazon.com/cli/) is a good option too

note: reopening issue so this doesn't get lost

**Comment by cll008** [comment]
Thanks Franklin. Is there a more tested / stable version combination you recommend? Or should I just try node 14 and latest openneuro-cli again?

**Comment by franklin-feingold** [comment]
perhaps trying node 14 with the latest version of the openneuro-cli - we are making active enhancements to the cli processes

**Comment by nellh** [comment]
What version of npm are you using? We're testing with npm 7 and yarn 1.22 - there could be a regression on npm 6 for example.

**Comment by cll008** [comment]
Unfortunately no luck with npm 7 either, will try it on another system and then try yarn.

**Comment by nellh** [comment]
@cll008 I've narrowed down the issue and a fix will be in the next release (which is tomorrow). It is not related to a specific version of npm or yarn.

**Comment by nellh** [comment]
openneuro-cli@3.31.0 includes a fix for this, please give it a try and comment if you are still having issues.

**Comment by cll008** [comment]
Working now, npm@7.6.3 and openneuro-cli@3.31.0. Thanks so much.
