### ISSUE TITLE
ds003504 - upload timesout for a large dataset

### ISSUE THREAD

**Issue by Arshitha** [OpenNeuroOrg/openneuro#1969]
Hi, 

I am trying to upload a dataset which is about 340 GB in size through the openneuro-cli tool. On my first attempt, the upload command ran for about 2.5 days and errored out. The progress bar was stuck at 19% even though the upload seemed to continue based on the output to my terminal console. However, when I checked the repo on https://openneuro.org/datasets/ds003504 (I uploaded a couple of subject directories through the web-interface at a later point), the repository was empty except for the landing page. Following is the command I used and the error:

`openneuro upload <path-to-dataset> --ignoreWarnings --ignoreNiftiHeaders --ignoreSubjectConsistency --verbose`

```
FetchError: request to https://openneuro.org/crn/graphql failed, reason: connect ETIMEDOUT 99.83.251.54:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/openneuro-cli/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:311:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://openneuro.org/crn/graphql failed, reason: connect ETIMEDOUT 99.83.251.54:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

While there's an option to add subject directories through the web-interface, it wasn't possible with the following command through the cli tool since it tries to validate the subject directory - 

`openneuro upload -d ds003504 --ignoreWarnings --ignoreSubjectConsistency --verbose -n sub-ON01016`

Is there a flag that I could use to skip the bids validation? or a flag to upload just a file or a directory like on openneuro.org? 
And if upload fails, let's say, after 25% completion then why don't the files/directories appear on the openneuro.org repository? 

Also, if you have any tips or good practices on how to upload large datasets through the cli to avoid timeout related errors that would be very useful.  

Following are the version info for node, npm and openneuro-cli:
```bash
→ node -v
v12.16.1

→ npm -v
7.5.2

→ openneuro --version
3.28.0
```

**Comment by nellh** [comment]
Hi, thanks for this issue report. This points to a bug in how we retry a timeout in the CLI that I think we can fix for the next release.

You can break up datasets for upload by including the root level files and a subset of subjects. The CLI always takes the root of the dataset (with dataset_description.json) but it won't remove files that exist in the remote dataset if they are not present locally.

The files aren't committed to the dataset until an upload is completed to prevent partial uploads from leading to inconsistent datasets. If you retry the upload with the same set of input files, it should skip the ones that OpenNeuro has (but it will start from scratch if files have changed).

**Comment by Arshitha** [comment]
Thanks @nellh

**Comment by Arshitha** [comment]
hi @nellh - I am uploading the dataset in smaller chunks of 5 subjects per upload but I've received the following error a couple of times without affecting the upload itself. 

```
Starting a new upload (468f71d0) to dataset: 'ds003504'
ds003504 [=====-----------------------------------] 13% | ETA: 3682s | 96/700(node:10149) UnhandledPromiseRejectionWarning:d
    at Object.makeAbortedError (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dis)
    at /spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dist/lib/fetch-http2.js:63:39
    at ClientHttp2Stream.<anonymous> (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/callgu)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/home/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/elas)
    at ClientHttp2Stream.emit (events.js:315:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:482:12)
    at closeStream (internal/http2/core.js:1747:14)
    at Http2Stream.onStreamClose (internal/http2/core.js:505:5)
(node:10149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside)
(node:10149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections t.
(node:10149) UnhandledPromiseRejectionWarning: Error: Request aborted
    at Object.makeAbortedError (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dis)
    at /spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dist/lib/fetch-http2.js:63:39
    at ClientHttp2Stream.<anonymous> (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/callgu)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/home/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/elas)
    at ClientHttp2Stream.emit (events.js:315:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:482:12)
    at closeStream (internal/http2/core.js:1747:14)
    at Http2Stream.onStreamClose (internal/http2/core.js:505:5)
(node:10149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside)
(node:10149) UnhandledPromiseRejectionWarning: Error: Request aborted
    at Object.makeAbortedError (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dis)
    at /spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dist/lib/fetch-http2.js:63:39
    at ClientHttp2Stream.<anonymous> (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/callgu)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/home/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/elas)
    at ClientHttp2Stream.emit (events.js:315:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:482:12)
    at closeStream (internal/http2/core.js:1747:14)
    at Http2Stream.onStreamClose (internal/http2/core.js:505:5)
(node:10149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside)
(node:10149) UnhandledPromiseRejectionWarning: Error: Request aborted
    at Object.makeAbortedError (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dis)
    at /spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/fetch-h2/dist/lib/fetch-http2.js:63:39
    at ClientHttp2Stream.<anonymous> (/spin1/home/linux/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/callgu)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/home/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/elas)
    at ClientHttp2Stream.emit (events.js:315:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:482:12)
    at closeStream (internal/http2/core.js:1747:14)
    at Http2Stream.onStreamClose (internal/http2/core.js:505:5)
(node:10149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside)
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:80:15)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/home/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/elas)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:482:12)
    at closeStream (internal/http2/core.js:1747:14)
    at Http2Stream.onStreamClose (internal/http2/core.js:505:5) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Error [ERR_STREAM_PREMATURE_CLOSE] [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (internal/streams/end-of-stream.js:80:15)
    at ClientHttp2Stream.elasticAPMCallbackWrapper (/home/arshithab/.local/lib/node_modules/openneuro-cli/node_modules/elas)
    at ClientHttp2Stream.emit (events.js:327:22)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:482:12)
    at closeStream (internal/http2/core.js:1747:14)
    at Http2Stream.onStreamClose (internal/http2/core.js:505:5) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
ds003504 [=======---------------------------------] 17% | ETA: 3473s | 124/700
```
I'm not sure what it means but just wanted to confirm if this is something that I need to be concerned about.

**Comment by ckrountree** [comment]
### SPRINT REVIEW
tried uploading a large dataset (ds001533) to confirm it is now working properly.
![Screen Shot 2021-02-22 at 11 35 17 AM](https://user-images.githubusercontent.com/27043528/108760085-0e959300-7502-11eb-933f-ed9b82e76942.png)

**Comment by Arshitha** [comment]
Thank you!
