### ISSUE TITLE
SSR crashes with `Cannot use import statement outside a module` in rc-motion library

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#2175]
**Describe the bug**
SSR crashes on master

**To Reproduce**
1. Visit the site
1. The app container throws this error

**Additional context**
```
app_1            | 8:40:16 PM [vite] Error when evaluating SSR module /@fs/srv/.yarn/$$virtual/rc-motion-virtual-dcb6cae8f3/0/cache/rc-motion-npm-2.4.3-e14c5457c0-8258fd1b6f.zip/node_modules/rc-motion/es/util/motion.js:
app_1            | /srv/.yarn/cache/@babel-runtime-npm-7.14.0-fba2a32266-ab6653f2f8.zip/node_modules/@babel/runtime/helpers/esm/typeof.js:1
app_1            | export default function _typeof(obj) {
app_1            | ^^^^^^
app_1            | 
app_1            | SyntaxError: Unexpected token 'export'
app_1            |     at wrapSafe (internal/modules/cjs/loader.js:979:16)
app_1            |     at Module._compile (internal/modules/cjs/loader.js:1027:27)
app_1            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
app_1            |     at Module.load (internal/modules/cjs/loader.js:928:32)
app_1            |     at Function.external_module_.Module._load (/srv/.pnp.js:53716:14)
app_1            |     at Module.require (internal/modules/cjs/loader.js:952:19)
app_1            |     at require (internal/modules/cjs/helpers.js:88:18)
app_1            |     at nodeRequire (/srv/.yarn/cache/vite-npm-2.3.1-c58e3980f3-4bb6cc6df2.zip/node_modules/vite/dist/node/chunks/dep-bc4956ea.js:68067:17)
app_1            |     at ssrImport (/srv/.yarn/cache/vite-npm-2.3.1-c58e3980f3-4bb6cc6df2.zip/node_modules/vite/dist/node/chunks/dep-bc4956ea.js:68020:20)
app_1            |     at eval (/@fs/srv/.yarn/$$virtual/rc-motion-virtual-dcb6cae8f3/0/cache/rc-motion-npm-2.4.3-e14c5457c0-8258fd1b6f.zip/node_modules/rc-motion/es/util/motion.js:3:31)
app_1            | 8:40:16 PM [vite] Error when evaluating SSR module /@fs/srv/.yarn/$$virtual/rc-align-virtual-a38da8f648/0/cache/rc-align-npm-4.0.9-aa837a6709-28c74fd133.zip/node_modules/rc-align/es/util.js:
app_1            | /srv/.yarn/cache/@babel-runtime-npm-7.14.0-fba2a32266-ab6653f2f8.zip/node_modules/@babel/runtime/helpers/esm/slicedToArray.js:1
app_1            | import arrayWithHoles from "./arrayWithHoles.js";
app_1            | ^^^^^^
app_1            | 
app_1            | SyntaxError: Cannot use import statement outside a module
app_1            |     at wrapSafe (internal/modules/cjs/loader.js:979:16)
app_1            |     at Module._compile (internal/modules/cjs/loader.js:1027:27)
app_1            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
app_1            |     at Module.load (internal/modules/cjs/loader.js:928:32)
app_1            |     at Function.external_module_.Module._load (/srv/.pnp.js:53716:14)
app_1            |     at Module.require (internal/modules/cjs/loader.js:952:19)
app_1            |     at require (internal/modules/cjs/helpers.js:88:18)
app_1            |     at nodeRequire (/srv/.yarn/cache/vite-npm-2.3.1-c58e3980f3-4bb6cc6df2.zip/node_modules/vite/dist/node/chunks/dep-bc4956ea.js:68067:17)
app_1            |     at ssrImport (/srv/.yarn/cache/vite-npm-2.3.1-c58e3980f3-4bb6cc6df2.zip/node_modules/vite/dist/node/chunks/dep-bc4956ea.js:68020:20)
app_1            |     at eval (/@fs/srv/.yarn/$$virtual/rc-align-virtual-a38da8f648/0/cache/rc-align-npm-4.0.9-aa837a6709-28c74fd133.zip/node_modules/rc-align/es/util.js:3:31)
app_1            | 8:40:16 PM [vite] Error when evaluating SSR module /@fs/srv/.yarn/$$virtual/rc-util-virtual-5289bc9b55/0/cache/rc-util-npm-5.12.1-4c61e0d389-07cb7e9419.zip/node_modules/rc-util/es/raf.js?v=3414ac58:
app_1            | ReferenceError: wrapperRaf is not defined
app_1            |     at /@fs/srv/.yarn/$$virtual/rc-util-virtual-5289bc9b55/0/cache/rc-util-npm-5.12.1-4c61e0d389-07cb7e9419.zip/node_modules/rc-util/es/raf.js?v=3414ac58:51:1
app_1            |     at instantiateModule (/srv/.yarn/cache/vite-npm-2.3.1-c58e3980f3-4bb6cc6df2.zip/node_modules/vite/dist/node/chunks/dep-bc4956ea.js:68053:166)
```

**Comment by nellh** [comment]
Related issue: https://github.com/react-component/motion/issues/14
