### ISSUE TITLE
initremote with openneuro not working

### ISSUE THREAD

**Issue by bpinsard** [OpenNeuroOrg/openneuro#2322]
**Describe the bug**
*A clear and concise description of what the bug is.*
I am trying to follow that part of the doc to add an openneuro special remote. 
https://docs.openneuro.org/git#git-annex-special-remote
But I cannot manage to make it work.

**To Reproduce**

I first installed the npm package:

```
sudo npm install -g openneuro-cli
npm WARN deprecated openneuro-cli@3.32.4: This package has been replaced with @openneuro/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/openneuro -> /usr/local/lib/node_modules/openneuro-cli/src/index.js
/usr/local/bin/git-credential-openneuro -> /usr/local/lib/node_modules/openneuro-cli/src/index.js
/usr/local/bin/git-annex-remote-openneuro -> /usr/local/lib/node_modules/openneuro-cli/src/index.js

> aws-crt@1.9.1 install /usr/local/lib/node_modules/openneuro-cli/node_modules/aws-crt
> node ./scripts/install.js

npm WARN notsup Unsupported engine for openneuro-cli@3.32.4: wanted: {"node":">=12.9.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: openneuro-cli@3.32.4

+ openneuro-cli@3.32.4
added 567 packages from 420 contributors in 42.118s
```
It tells me that this package is replaced with a newer version, but let's first try that old one.

```
$ echo "EXTENSIONS" | git-annex-remote-openneuro

```
it returns nothing, so git-annex initremote fails below

```
$ git annex initremote openneuro_sub01 type=external externaltype=openneuro encryption=none url=https://openneuro.org/git/2/ds003788
initremote openneuro_sub01 
git-annex: external special remote protocol error, unexpectedly received "" (unable to parse command)
failed
git-annex: initremote: 1 failed
```

Let's try the more recent package suggested above:

```
sudo npm uninstall -g openneuro-cli
....

sudo npm install -g @openneuro/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/git-annex-remote-openneuro -> /usr/local/lib/node_modules/@openneuro/cli/src/index.js
/usr/local/bin/git-credential-openneuro -> /usr/local/lib/node_modules/@openneuro/cli/src/index.js
/usr/local/bin/openneuro -> /usr/local/lib/node_modules/@openneuro/cli/src/index.js

> aws-crt@1.9.1 install /usr/local/lib/node_modules/@openneuro/cli/node_modules/aws-crt
> node ./scripts/install.js

npm WARN notsup Unsupported engine for @openneuro/cli@3.35.3: wanted: {"node":">=12.9.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @openneuro/cli@3.35.3

+ @openneuro/cli@3.35.3
added 633 packages from 420 contributors in 14.205s
```
Installs, but there is a warning related to node engine version.
Let's try it anyway.

```
$ echo "EXTENSIONS" | git-annex-remote-openneuro
Usage: git-annex-remote-openneuro [options] [command]

OpenNeuro command line tools.

Options:
  -V, --version                                   output the version number
  -h, --help                                      display help for command

Commands:
  login|l                                         Setup authentication with OpenNeuro
  upload|u [options] <dir>                        Upload or sync a dataset (if an accession number is provided)
  download|d [options] <datasetId> <destination>  Download a dataset draft or snapshot. If neither is specified, will prompt with available snapshots.
  git-credential <operation>                      A git credentials helper for easier datalad or git-annex access to datasets.
  create-dataset|c                                Create a new empty dataset, useful for adding existing DataLad or git-annex datasets.
  help [command]                                  display help for command

See additional options for each command with "openneuro [command] --help". Example:
  $ openneuro upload --help
```
Doesn't like the request, initremote fails. 

Did I missed a step (I am not familiar with NodeJS), or is the doc not up-to-date?
Thanks for you help?

**Desktop (please complete the following information):**
- OS: Ubuntu
 - Browser: NA
 - Version: NA

**Smartphone (please complete the following information):**
- [x] Not applicable 

**Additional context**
*Add any other context about the problem here.*

**Comment by bpinsard** [comment]
Tried to dumbly log `process.argv[1]` in `cli.js` and it seems that lines https://github.com/OpenNeuroOrg/openneuro/blob/master/packages/openneuro-cli/src/cli.js#L73-L79 after `commander.parse` never get called when running the command line without args. Maybe `parse` directly calls `help` and exits when required args are not present? In certain version of `commander` package?

**Comment by bpinsard** [comment]
Any idea on this one?
I commented the line that calls the parser as such
```
//commander.parse(process.argv)
```

and tried
```
$ echo "EXTENSIONS" | git-annex-remote-openneuro
VERSION 1
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (events.js:135:11)
    at _addListener (events.js:433:3)
    at Interface.addListener (events.js:497:10)
    at gitAnnexRemote (/usr/lib/node_modules/@openneuro/cli/src/gitAnnexRemote.js:87:8)
    at Object.<anonymous> (/usr/lib/node_modules/@openneuro/cli/src/cli.js:76:3)
    at Generator.next (<anonymous>)
    at bl (/usr/lib/node_modules/@openneuro/cli/node_modules/esm/esm.js:1:245412)
    at kl (/usr/lib/node_modules/@openneuro/cli/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/lib/node_modules/@openneuro/cli/node_modules/esm/esm.js:1:287740)
    at Object.o (/usr/lib/node_modules/@openneuro/cli/node_modules/esm/esm.js:1:287137) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Thanks!

**Comment by effigies** [comment]
Did upgrading node to >=12.9 help?

**Comment by bpinsard** [comment]
Unfortunately not, I tried 16 and 14 and get the same issues.
Do you manage to get that package running on your side?

**Comment by bpinsard** [comment]
Sorry to be a bit pushy, I would like to find out if the problem is on my side and it would help to know if the current version works for others. Thanks!

**Comment by nellh** [comment]
> Sorry to be a bit pushy, I would like to find out if the problem is on my side and it would help to know if the current version works for others. Thanks!

I believe this is a regression and I'm working on tests and a fix for it, I'll update this issue once it's available in a release where you could test the fix.

**Comment by bpinsard** [comment]
Fantastic, thanks @nellh for the fast fixes, will try them out asap.
