### ISSUE TITLE
TypeError: u.defaultValue.split is not a function

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#243]
I was trying to add a multicheck input with for FMRIPREP with following default options "template fsaverage".

https://sentry.io/openneuro/openneuro/issues/413504414/

```
TypeError: u.defaultValue.split is not a function
  at t.submitJobDefinition (./scripts/admin/admin.store.js:327:47)
  at a (../node_modules/reflux-core/lib/PublisherMethods.js:53:1)
  at a.emit (../node_modules/eventemitter3/index.js:116:1)
  at Function.t.trigger (../node_modules/reflux-core/lib/PublisherMethods.js:71:1)
  at e (../node_modules/reflux-core/lib/createAction.js:81:1)
...
(18 additional frame(s) were not displayed)
```

**Comment by chrisgorgo** [comment]
This turned out to be a weird confluence of incorrect memory requirements (with the error message blurred in the background) and the modal trying to "fix" the values. Unlikely that anyone will run into this again.

**Comment by Xesme** [comment]
I have recreated this bug message. It occurs when there is an error on a new app submission. On the second attempt to submit app definition it will throw error. Looking into how to resolve this issue.
