### ISSUE TITLE
Installing cli crashes because of missing CMake

### ISSUE THREAD

**Issue by timo-berg** [OpenNeuroOrg/openneuro#2478]
**Describe the bug**
*Trying to install the cli via npm fails because cmake is missing despite it being installed (via npm).*

**To Reproduce**
1. Install cmake via `sudo npm install -g cmake-js`
2. Install openneuro-cli via `sudo npm install -g @openneuro/cli`

**Expected behavior**
*Successful installation of openneuro-cli*

**Desktop (please complete the following information):**
- OS: macOS Big Sur 11.6

**Additional context**
Executing `cmake-js -h` shows CMake's help and it's version `CMake.js 6.2.1`. So I'm assuming CMake is correctly installed?

Error:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'elastic-apm-node@3.12.1',
npm WARN EBADENGINE   required: { node: '^8.6.0 || 10 || 12 || 13 || 14' },
npm WARN EBADENGINE   current: { node: 'v17.1.0', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@openneuro/cli/node_modules/aws-crt
npm ERR! command failed
npm ERR! command sh -c node ./scripts/install.js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info TOOL Building only the install target, as specified from the command line.
npm ERR! info DIST Downloading distribution files.
npm ERR! http DIST 	- https://nodejs.org/dist/v17.1.0/SHASUMS256.txt
npm ERR! http DIST 	- https://nodejs.org/dist/v17.1.0/node-v17.1.0-headers.tar.gz
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! /usr/local/lib/node_modules/@openneuro/cli/node_modules/cmake-js/lib/cMake.js:115
npm ERR!         throw new Error("CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.");
npm ERR!               ^
npm ERR! 
npm ERR! Error: CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR!     at CMake.verifyIfAvailable (/usr/local/lib/node_modules/@openneuro/cli/node_modules/cmake-js/lib/cMake.js:115:15)
npm ERR!     at CMake.build (/usr/local/lib/node_modules/@openneuro/cli/node_modules/cmake-js/lib/cMake.js:287:10)
npm ERR!     at BuildSystem._invokeCMake (/usr/local/lib/node_modules/@openneuro/cli/node_modules/cmake-js/lib/buildSystem.js:59:40)
npm ERR!     at async buildFromRemoteSource (/usr/local/lib/node_modules/@openneuro/cli/node_modules/aws-crt/scripts/build.js:148:5)
npm ERR! 
npm ERR! Node.js v17.1.0
```

**Comment by effigies** [comment]
I believe you need the actual cmake tool installed.

**Comment by timo-berg** [comment]
Tried that as well without success

**Comment by effigies** [comment]
The package that's failing to install seems to be [aws-crt](https://github.com/awslabs/aws-crt-nodejs#building-the-package). Might be worth checking their installation instructions to troubleshoot.

**Comment by timo-berg** [comment]
Found the problem. Cmake wasn't in the path. Only cmake-js was...
