### ISSUE TITLE
Error creating new versions "cannot PUT /doi/10.1882/openneuro.ds00XXXX.v1.0.X"

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2724]
**Describe the bug**
Two dataset owners report not being able to create new snapshots of their datasets. In both cases the datasets were previously published and the draft is validating.

**To Reproduce**
1. Go to https://openneuro.org/datasets/ds004348/snapshot
2. Add changelog entry "Rearranged code files" (requested by user)
3. Attempt to make snapshot
4. Never-ending throbber

**Expected behavior**

New snapshot.

**Additional context**

The datasets can both be found by searching the error console for "error cannot put".

Sample stack trace:

```
 error: Error: cannot PUT /doi/10.18112/openneuro.ds004348.v1.0.1 (502)
        at Response.toError (/srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/node/response.js:94:15)
        at ResponseBase._setStatusProperties (/srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/response-base.js:123:16)
        at new Response (/srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/node/response.js:41:8)
        at Request._emitResponse (/srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/node/index.js:752:20)
        at IncomingMessage.<anonymous> (/srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/node/index.js:916:38)
        at /srv/.yarn/cache/elastic-apm-node-npm-3.31.0-4bfad53eb8-5153505d96.zip/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
        at AsyncHooksRunContextManager.with (/srv/.yarn/cache/elastic-apm-node-npm-3.31.0-4bfad53eb8-5153505d96.zip/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:49:17)
        at IncomingMessage.wrapper (/srv/.yarn/cache/elastic-apm-node-npm-3.31.0-4bfad53eb8-5153505d96.zip/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
        at IncomingMessage.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { 
```

**Comment by nellh** [comment]
This is an upstream issue with Datacite.

Error handling should be improved here though, we could show something like Datacite timed out and try again later.

**Comment by nellh** [comment]
Looks like Datacite resolved these issues and this should be working now.
