### ISSUE TITLE
CLI upload may throw ERR_STREAM_PREMATURE_CLOSE on retried requests

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#2786]
### What went wrong?

While uploading, if a request needs to be retried you can get this error originating from the failed request stream.

```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:372:5)
    at ClientHttp2Stream.onclose (node:internal/streams/end-of-stream:141:30)
    at ClientHttp2Stream.emit (node:events:539:35)
    at ClientHttp2Stream.emit (node:domain:475:12)
    at closeStream (node:internal/http2/core:1917:14)
    at Http2Stream.onStreamClose (node:internal/http2/core:543:5)
    at Http2Stream.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```

### Expected behavior

This should be gracefully closed in this case, instead of canceled destructively to avoid the error and dangling socket handles.

### How to reproduce

Simulating packet loss and uploading a dataset with larger files such as nifti images will generally throw this on the larger files after a few attempts.

### Desktop

- OS: Ubuntu 22.10
- Browser: Node.js
- Version: 18.15.0

**Comment by jrudoler** [comment]
@nellh having this issue uploading using cli for `ds004706`. EEG files ~3-4GB won't upload and throw many errors like:
```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at ClientHttp2Stream.onclose (node:internal/streams/end-of-stream:147:30)
    at /home1/jrudoler/node/lib/node_modules/@openneuro/cli/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:49
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at AsyncLocalStorageRunContextManager.with (/home1/jrudoler/node/lib/node_modules/@openneuro/cli/node_modules/elastic-apm-node/lib/instrumentation/run-context/AsyncLocalStorageRunContextManager.js:57:36)
    at ClientHttp2Stream.wrapper (/home1/jrudoler/node/lib/node_modules/@openneuro/cli/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:23)
    at ClientHttp2Stream.emit (node:events:525:35)
    at ClientHttp2Stream.emit (node:domain:489:12)
    at closeStream (node:internal/http2/core:1919:14)
    at Http2Stream.onStreamClose (node:internal/http2/core:544:5)
    at Http2Stream.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```
Smaller files seem to have gone through. Using node version v18.12.1 and openneuro v4.19.3.
