### ISSUE TITLE
Sharing derivatives only 

### ISSUE THREAD

**Issue by MerveKaptan** [OpenNeuroOrg/openneuro#2868]
Dear @effigies ,

I hope you are doing well!
We have talked about this in the following ticket: https://openneuro.freshdesk.com/helpdesk/tickets/1525, about sharing derivatives only datasets consisting of motion-corrected EPI volumes, mean of these volumes, and a binary mask. We do not have access to the source/raw data.

Could we please move the thread here so everyone on the project could see the comments/replies?

I also do have a few follow-up questions. We would like to share the datasets sooner than later!

- Could we treat the motion-corrected volumes that I have mentioned in the ticket as the source data?
- Could we treat the mean of motion-corrected volumes as the source data as well?

In this case, the binary masks will be derivatives.

Would these be fine?
Thank you so much and looking forward to your response!
Merve

**Comment by effigies** [comment]
Hi Merve, to be clear, I think you're proposing:

```
dataset/
├── dataset_description.json
├── derivatives/
│   ├── dataset_description.json
│   └── sub-01
│       └── func
│           └── sub-01_task-rest_desc-spinalcord_mask.nii.gz  <---- Manual spinal cord segmentation
├── sub-01
│   └── func
│       ├── sub-01_task-rest_bold.json       <---- sidecar json file containing imaging parameters
│       ├── sub-01_task-rest_bold.nii.gz     <---- 20 motion-corrected EPI volumes                 
│       └── sub-01_task-rest_desc-mocomean_bold.nii.gz <---- Mean of motion-corrected volumes
├── participants.json
├── participants.tsv
└── task-rest_bold.json
```

This would be okay, except `desc-mocomean` would be a derivative filename, and it's not really a BOLD file so much as a mean bold. It will be painful to convince the validator that this is legitimate. Something like this could work:

```
dataset/
├── dataset_description.json
├── derivatives/
│   ├── dataset_description.json
│   └── sub-01
│       └── func
│           ​├── sub-01_task-rest_desc-mocomean_bold.nii.gz <---- Mean of motion-corrected volumes
│           └── sub-01_task-rest_desc-spinalcord_mask.nii.gz  <---- Manual spinal cord segmentation
├── sub-01
│   └── func
│       ├── sub-01_task-rest_bold.json       <---- sidecar json file containing imaging parameters
│       └── sub-01_task-rest_bold.nii.gz     <---- 20 motion-corrected EPI volumes                 
├── participants.json
├── participants.tsv
└── task-rest_bold.json
```

Note that calling a mean image a "bold image" is a bit out of BIDS intent, which defines BOLD as a 4D timeseries (though I'm not sure if the validator would be smart enough to catch it). Right now, according to [BEP012 - Functional derivatives](https://bids-specification.readthedocs.io/en/bep012/derivatives/functional-derivatives.html), this type of derivative would be `sub-01_task-rest_stat-mean_boldmap.nii.gz`.

Note that that proposal has not been accepted, and it's subject to change, but that shouldn't hold you up. If you think that or similar would be clear enough to the consumers of your dataset, you can go ahead and adopt it.

WDYT?

**Comment by MerveKaptan** [comment]
Hi @effigies ,

Thank you so much for the suggestions! The organization you suggested seems clear and understandable to me! 

When we have a one-volume image, the validator gives a warning, not an error, which would be fine (I think). 
So, you suggest keeping the mask and mean image within the same folder instead of separating them, right?

thank you very much!

**Comment by effigies** [comment]
> So, you suggest keeping the mask and mean image within the same folder instead of separating them, right?

My suggestion would be to do whatever is needed to clearly communicate to your colleagues the information you want them to know. If that means splitting into multiple subdirectories, I have no objection. My initial suggestion to combine was based on wanting a single dataset where everything was presented as a derivative, in which case combining is the only way to do it. Once you've settled on a raw dataset with derivative subdataset(s), that motivation goes away.

**Comment by MerveKaptan** [comment]
I see, thank you very very much for the replies - super helpful!

**Comment by MerveKaptan** [comment]
Hello again! 

We would like to upload the data soon! I wanted to ask whether you have a solution for uploading derivatives only or should we go ahead and divide the data between source and derivative?

Thank you very much,
Merve

**Comment by effigies** [comment]
Hi, thanks for checking in. If you have the data organized according to the derivative-only structure, does it validate with https://deno.land/x/bids_validator (instructions on [this page](https://github.com/bids-standard/bids-validator/tree/master/bids-validator/src#usage), though they should update to the deno.land page on the next release)? 

We are not quite ready to roll out the derivatives uploads, so if you need to upload ASAP, or the answer to the above question is "No", then I would go ahead with the "raw" dataset with bundled derivatives. If the validator passes and you're okay waiting a little bit longer, then @nellh would be best positioned to give you an estimate of when we could try uploading.

**Comment by nellh** [comment]
This should be included in OpenNeuro 4.20.0 for web uploads (CLI uploads will be in a later release). That release is fairly close, I expect to deploy it next week sometime.

**Comment by nellh** [comment]
@MerveKaptan To keep you up to date, this release is still pending deployment for a few fixes. It is available on our staging site now, if you'd like it would be great to get feedback on any blockers uploading your dataset there. https://staging.openneuro.org/

**Comment by MerveKaptan** [comment]
Dear @nellh and @effigies,

Thank you very much, I really appreciate the support!
@nellh  I am trying to upload one dataset in the original derivatives-only format. It is taking a long time for the validation process but I will keep you updated if I will be able to successfully pass the validation or not!

Thank you very much,
Merve

**Comment by MerveKaptan** [comment]
Dear @nellh,

I am trying to upload one dataset to the following as you suggested https://staging.openneuro.org/.  However, it gets stuck at the validation stage. Actually, it has been trying to validate a small dataset since yesterday - I do not even get to a stage where I get an error message. 


Dear @effigies,

I have tried the deno validator, as far as I can see, I was not able to detect the number of subjects and so on with the original scheme that I have. 

```
/home/mkaptan/.deno/bin/deno run --allow-read --allow-env https://deno.land/x/bids_validator/bids-validator.ts /home/mkaptan/Projects/fmri_spinal_cord_segmentation/Datasets/data_stanford_rest/
Warning Implicitly using latest version (v1.13.2-dev.0) for https://deno.land/x/bids_validator/bids-validator.ts
error: Uncaught (in promise) SyntaxError: Expected ',' or '}' after property value in JSON at position 1444 (line 10 column 6)
    const description = await ddFile.text().then((text) => JSON.parse(text))
                                                                ^
    at JSON.parse (<anonymous>)
    at https://deno.land/x/bids_validator@v1.13.2-dev.0/validators/bids.ts:49:65
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async validate (https://deno.land/x/bids_validator@v1.13.2-dev.0/validators/bids.ts:49:25)
    at async main (https://deno.land/x/bids_validator@v1.13.2-dev.0/main.ts:16:24)
    at async https://deno.land/x/bids_validator@v1.13.2-dev.0/bids-validator.ts:3:1
mkaptan@Mackeylab200:~$ /home/mkaptan/.deno/bin/deno run --allow-read --allow-env https://deno.land/x/bids_validator/bids-validator.ts /home/mkaptan/Projects/fmri_spinal_cord_segmentation/Datasets/data_leipzig_pain
	[WARNING] The 'Authors' field of 'dataset_description.json' should contain an array of values -
with one author per value.
This was triggered based on the presence of only one author field.
Please ignore if all contributors are already properly listed.
 (TOO_FEW_AUTHORS)

		./dataset_description.json
			Evidence: schema.rules.checks.hints.TooFewAuthors

		1 more files with the same issue

	Please visit https://neurostars.org/search?q=TOO_FEW_AUTHORS for existing conversations about this issue.

	[ERROR] A data file's JSON sidecar is missing a key listed as required. (JSON_KEY_REQUIRED)

		./dataset_description.json
			Evidence: missing BIDSVersion as per schema.rules.dataset_metadata.dataset_description

		1 more files with the same issue

	Please visit https://neurostars.org/search?q=JSON_KEY_REQUIRED for existing conversations about this issue.


          Summary:                         Available Tasks:        Available Modalities:
          3 Files, 3.71 kB                 pain                                         
          **0 - Subjects 1 - Sessions**                                                     

	If you have any questions, please post on https://neurostars.org/tags/bids.

```


Given these, I believe it would be easier to treat these dataset(s) as "regular" BIDS datasets with source and derivatives folder. Would you agree?


Thank you so much, I really appreciate the support!
Merve

**Comment by yarikoptic** [comment]
> Given these, I believe it would be easier to treat these dataset(s) as "regular" BIDS datasets with source and derivatives folder. Would you agree?

smells like a use case for "bids study" datasets: https://bids-specification.readthedocs.io/en/stable/common-principles.html#study-dataset but those aren't ATM supported by OpenNeuro AFAIK.

But overall, @MerveKaptan , given the passed time -- is there anything else to be done for this issue or could it be closed?

**Comment by MerveKaptan** [comment]
Hi @yarikoptic ,

thanks a lot!!
We did the following: https://openneuro.org/datasets/ds005143/versions/1.3.1

Best,
Merve
