### ISSUE TITLE
Premature close error for large files

### ISSUE THREAD

**Issue by jrudoler** [OpenNeuroOrg/openneuro#2874]
@nellh having this issue uploading using cli for `ds004706`. EEG files ~3-4GB won't upload and throw many errors like:
```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at ClientHttp2Stream.onclose (node:internal/streams/end-of-stream:147:30)
    at /home1/jrudoler/node/lib/node_modules/@openneuro/cli/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:49
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at AsyncLocalStorageRunContextManager.with (/home1/jrudoler/node/lib/node_modules/@openneuro/cli/node_modules/elastic-apm-node/lib/instrumentation/run-context/AsyncLocalStorageRunContextManager.js:57:36)
    at ClientHttp2Stream.wrapper (/home1/jrudoler/node/lib/node_modules/@openneuro/cli/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:23)
    at ClientHttp2Stream.emit (node:events:525:35)
    at ClientHttp2Stream.emit (node:domain:489:12)
    at closeStream (node:internal/http2/core:1919:14)
    at Http2Stream.onStreamClose (node:internal/http2/core:544:5)
    at Http2Stream.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```
Smaller files seem to have gone through. Using node version v18.12.1 and openneuro v4.19.3.

_Originally posted by @jrudoler in https://github.com/OpenNeuroOrg/openneuro/issues/2786#issuecomment-1683153535_

**Comment by tsalo** [comment]
I'm getting the same error when I try to upload a datalad dataset, using openneuro v4.24.2. I'm just wondering, does anyone know what causes this?

**Comment by effigies** [comment]
What version of node are you using?

**Comment by tsalo** [comment]
v20.9.0

**Comment by tsalo** [comment]
FWIW, no files seem to be uploaded at all (not even small ones). It could be that I was killing the process before it reached small files, but I would think that the `dataset_description.json` would be the first thing uploaded. The new dataset is being created with a new ID, but it doesn't show up on my "My Datasets" page.

**Comment by tsalo** [comment]
I'm not sure how, but it seems to be working now. The only thing I've done differently is I installed deno so I could test out the schema-based validator.

EDIT: Never mind. It started giving me the ERR_STREAM_PREMATURE_CLOSE error at 6%. When I tried restarting the upload to the dataset it created, I get a `graphQLError` with the message "Not Found".

**Comment by DVSneuro** [comment]
I think we're getting the same error with some fMRI data. We're using node v20.17.0 and openneuro 4.27.0. 

```
ds005085 [==--------------------------------------] 4% | ETA: 153s | 352/7178Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ClientHttp2Stream.onclose (node:internal/streams/end-of-stream:159:30)
    at ClientHttp2Stream.emit (node:events:531:35)
    at closeStream (node:internal/http2/core:1946:14)
    at Http2Stream.onStreamClose (node:internal/http2/core:556:5) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```

We're basically just trying to update and existing dataset with the command below:
`openneuro upload --dataset ds005085 --ignoreWarnings bids`

Are there any alternatives to bulk updating a dataset via the web-based interface? It looks like the "update" option is only available on a per file basis, which isn't practical when there are thousands of files to update. I saw some discussion of fixes/enhancements in https://github.com/OpenNeuroOrg/openneuro/issues/387 and https://github.com/OpenNeuroOrg/openneuro/issues/2834 and https://github.com/OpenNeuroOrg/openneuro/issues/1067. Any ideas @nellh ?

Thanks!
David

**Comment by DVSneuro** [comment]
I tried the latest version of OpenNeuro (4.28.1), and I'm still getting the same upload error from the command line. Seems like an issue on the server end? 

Are there any alternatives to bulk updating datasets on the web-based interfaced?

Thanks!
David

```
ds005085 [========================================] 100% | ETA: 0s | 7408/7408
Error [ServerError]: Response not successful: Received status code 502
    at Object.throwServerError (/home/tug87422@tu.temple.edu/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/utils/utils.cjs:45:17)
    at parseJsonBody (/home/tug87422@tu.temple.edu/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/http/http.cjs:275:15)
    at /home/tug87422@tu.temple.edu/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/http/http.cjs:311:48
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://openneuro.org/crn/graphql',
      status: 502,
      statusText: 'Bad Gateway',
      headers: [Headers],
      counter: 0
    }
  },
  statusCode: 502,
  result: '\n' +
    '<html><head>\n' +
    '<meta http-equiv="content-type" content="text/html;charset=utf-8">\n' +
    '<title>502 Server Error</title>\n' +
    '</head>\n' +
    '<body text=#000000 bgcolor=#ffffff>\n' +
    '<h1>Error: Server Error</h1>\n' +
    '<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n' +
    '<h2></h2>\n' +
    '</body></html>\n'
}

```

**Comment by nellh** [comment]
> I tried the latest version of OpenNeuro (4.28.1), and I'm still getting the same upload error from the command line. Seems like an issue on the server end?
> 
> Are there any alternatives to bulk updating datasets on the web-based interfaced?
> 
> Thanks! David
> 
> ```
> ds005085 [========================================] 100% | ETA: 0s | 7408/7408
> Error [ServerError]: Response not successful: Received status code 502
>     at Object.throwServerError (/home/tug87422@tu.temple.edu/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/utils/utils.cjs:45:17)
>     at parseJsonBody (/home/tug87422@tu.temple.edu/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/http/http.cjs:275:15)
>     at /home/tug87422@tu.temple.edu/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/http/http.cjs:311:48
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   response: Response {
>     size: 0,
>     timeout: 0,
>     [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
>     [Symbol(Response internals)]: {
>       url: 'https://openneuro.org/crn/graphql',
>       status: 502,
>       statusText: 'Bad Gateway',
>       headers: [Headers],
>       counter: 0
>     }
>   },
>   statusCode: 502,
>   result: '\n' +
>     '<html><head>\n' +
>     '<meta http-equiv="content-type" content="text/html;charset=utf-8">\n' +
>     '<title>502 Server Error</title>\n' +
>     '</head>\n' +
>     '<body text=#000000 bgcolor=#ffffff>\n' +
>     '<h1>Error: Server Error</h1>\n' +
>     '<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n' +
>     '<h2></h2>\n' +
>     '</body></html>\n'
> }
> ```

Hi, thanks for reporting the issues.

There's a couple alternatives you could try. We have a new command line uploader that is planned to replace the Node.JS one soon, available for testing here. https://jsr.io/@openneuro/cli

Another option is to use DataLad to make your modifications. Documentation for that process is here: https://docs.openneuro.org/git.html

**Comment by DVSneuro** [comment]
@nellh thanks! The new command line uploader is great, but we still can't upload/update our dataset because it's not passing the bids validator. The dataset is valid when tested with `bids-validator@1.14.12` and `bids-validator@1.14.6`, so maybe the new command line version is just using an old version of the bids validator?


```
(base) tug87422@cla18994:/ZPOOL/data/projects/multiecho-pilot$ singularity run --cleanenv -B /ZPOOL/data/projects/multiecho-pilot/bids:/data /ZPOOL/data/tools/bids-validator-v1.14.12.sif /data --verbose --ignoreWarnings --ignoreSubjectConsistency
bids-validator@1.14.12
(node:869710) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
This dataset appears to be BIDS compatible.
        Summary:                    Available Tasks:                             Available Modalities: 
        7849 Files, 236.28GB        sharedreward                                 MRI                   
        64 - Subjects               TODO: full task name for sharedreward                              
        1 - Session                                                                                    


	If you have any questions, please post on https://neurostars.org/tags/bids.

```

**Comment by nellh** [comment]
> @nellh thanks! The new command line uploader is great, but we still can't upload/update our dataset because it's not passing the bids validator. The dataset is valid when tested with `bids-validator@1.14.12` and `bids-validator@1.14.6`, so maybe the new command line version is just using an old version of the bids validator?
> 
> ```
> (base) tug87422@cla18994:/ZPOOL/data/projects/multiecho-pilot$ singularity run --cleanenv -B /ZPOOL/data/projects/multiecho-pilot/bids:/data /ZPOOL/data/tools/bids-validator-v1.14.12.sif /data --verbose --ignoreWarnings --ignoreSubjectConsistency
> bids-validator@1.14.12
> (node:869710) Warning: Closing directory handle on garbage collection
> (Use `node --trace-warnings ...` to show where the warning was created)
> This dataset appears to be BIDS compatible.
>         Summary:                    Available Tasks:                             Available Modalities: 
>         7849 Files, 236.28GB        sharedreward                                 MRI                   
>         64 - Subjects               TODO: full task name for sharedreward                              
>         1 - Session                                                                                    
> 
> 
> 	If you have any questions, please post on https://neurostars.org/tags/bids.
> ```

This is using the new schema based validator, you can run it standalone for testing with `deno run -A jsr:@bids/validator`. It hasn't yet been packaged for Docker and Singularity (see https://github.com/bids-standard/bids-validator/issues/1963).

It may be legitimate issues uncovered by greater coverage in the new validator or a bug with either the schema or implementation. If the new errors seem like a bug, you can report that to the [BIDS validator repository](https://github.com/bids-standard/bids-validator/).

**Comment by DVSneuro** [comment]
@nellh -- great, thanks! We'll work through the new errors and warnings. If anything seems like a bug, we'll report to the BIDS validator repository. 

Question: if we go through the datalad route for uploading/updating, would we still have to get through this new schema based validator? I assume all upload routes (including the web-based version) will eventually require that the data pass this new schema based validator, but we were hoping to just get this dataset updated for an upcoming paper submission.

Thanks again!

**Comment by nellh** [comment]
> @nellh -- great, thanks! We'll work through the new errors and warnings. If anything seems like a bug, we'll report to the BIDS validator repository.
> 
> Question: if we go through the datalad route for uploading/updating, would we still have to get through this new schema based validator? I assume all upload routes (including the web-based version) will eventually require that the data pass this new schema based validator, but we were hoping to just get this dataset updated for an upcoming paper submission.
> 
> Thanks again!

The DataLad path is still using the legacy JavaScript validator. It will switch to the schema validator in an upcoming release of OpenNeuro but not in the next few weeks.

**Comment by nellh** [comment]
The new OpenNeuro command line tools are available and Node.js tools are now deprecated. This should handle larger uploads better but please report any new issues.

https://docs.openneuro.org/packages/openneuro-cli.html
