### ISSUE TITLE
git clone failing and consuming large amounts of memory

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2981]
### What went wrong?

```
$ git clone --verbose https://openneuro.org/git/0/ds004516
Cloning into 'ds004516'...
POST git-upload-pack (415 bytes)
remote: Enumerating objects: 16984, done.
remote: Counting objects: 100% (16984/16984), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: INTERNAL_ERROR (err 2)
fetch-pack: unexpected disconnect while reading sideband packet
fatal: protocol error: bad pack header
```

### Expected behavior

Successful clone

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

### Additional information

These deflections in memory seem to correspond to the attempts to clone:

![image](https://github.com/OpenNeuroOrg/openneuro/assets/83442/661e68c1-ced7-4b79-a120-710fd96eaea1)

The traceback I'm able to find in the logs is non-obvious:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 65, in handle
    util.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 641, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 128, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 130, in handle_request
    util.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 641, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base_async.py", line 113, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 387, in write_file
    self.write(item)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 346, in write
    util.write(self.sock, arg, self.chunked)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 298, in write
    return write_chunk(sock, data)
```

I do see `BlockingIOError: [Errno 11] Resource temporarily unavailable` nearby, but it's unclear where these are being raised in OpenNeuro code.

**Comment by nellh** [comment]
This dataset has a few images added to the git history which is causing this issue.

**Comment by nellh** [comment]
The large git objects have been annexed and this dataset can now be cloned from GitHub or OpenNeuro.
