### ISSUE TITLE
curl script generation times out on large datasets

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3011]
### What went wrong?

Attempting to download the curl script for ds003097 (~15k validated files + derivatives) appears to time out.

### Expected behavior

Eventual success.

### How to reproduce

1. https://openneuro.org/datasets/ds003097/versions/1.2.1/download
2. Click "Download shell script" link

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by effigies** [comment]
Attempting to run the following query fails:

```gql
query snapshot($datasetId: ID!, $tag: String!) {
  snapshot(datasetId: $datasetId, tag: $tag) {
    id
    downloadFiles {
      id
      directory
      filename
      urls
      size
    }
  }
}
```

With variables: `{"datasetId": "ds003097", "tag": "v1.2.1"}`

Getting response:

```json
{
  "data": {
    "snapshot": null
  },
  "errors": [
    {
      "message": "Not Found",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": [
        "snapshot"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Not Found",
          "    at Request.callback (/srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/node/index.js:706:15)",
          "    at /srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/node/index.js:916:18",
          "    at IncomingMessage.<anonymous> (/srv/.yarn/cache/superagent-npm-3.8.3-8bdf672d54-b13d030325.zip/node_modules/superagent/lib/node/parsers/json.js:19:7)",
          "    at /srv/.yarn/cache/elastic-apm-node-npm-4.3.0-65b27adc8a-b0a257800e.zip/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:49",
          "    at AsyncLocalStorage.run (node:async_hooks:327:14)",
          "    at AsyncLocalStorageRunContextManager.with (/srv/.yarn/cache/elastic-apm-node-npm-4.3.0-65b27adc8a-b0a257800e.zip/node_modules/elastic-apm-node/lib/instrumentation/run-context/AsyncLocalStorageRunContextManager.js:57:36)",
          "    at IncomingMessage.wrapper (/srv/.yarn/cache/elastic-apm-node-npm-4.3.0-65b27adc8a-b0a257800e.zip/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:95:23)",
          "    at IncomingMessage.emit (node:events:526:35)",
          "    at endReadableNT (node:internal/streams/readable:1359:12)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
        ]
      }
    }
  ],
  "extensions": {
    "openneuro": {
      "version": "4.22.0"
    }
  }
}
```

**Comment by nellh** [comment]
This is fixed in OpenNeuro 5.0.0.
