### ISSUE TITLE
ds003404 has large object and is not syncing to github

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3013]
### What went wrong?

Found while looking for a different problem on worker 1.

<details open><summary>Log screenshot</summary>
<p>

![image](https://github.com/OpenNeuroOrg/openneuro/assets/83442/47d59d30-4ea1-47ea-905f-01847e061d5a)

</p>
</details> 

<details><summary>Crappy copy-paste</summary>
<p>

```
2024-03-06 14:56:53.772
openneuro-prod-dataset-worker
2024-03-06T19:56:53Z <Greenlet at 0x7b5fc4212d40: export_dataset('/datasets/ds003404', {'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXV)> failed with CalledProcessError
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
subprocess.CalledProcessError: Command '['git', 'push', 'github', 'refs/tags/1.0.2:refs/heads/main']' returned non-zero exit status 1.
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
    raise CalledProcessError(retcode, cmd) # pylint:disable=undefined-variable
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
  File "/usr/local/lib/python3.11/site-packages/gevent/subprocess.py", line 340, in check_call
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
    subprocess.check_call(
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
  File "/srv/datalad_service/common/github.py", line 31, in github_export
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
    github_export(dataset_id, dataset_path, tags[-1].name)
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
  File "/srv/datalad_service/tasks/publish.py", line 83, in export_dataset
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
           ^^^^^^^^^^^^^^^^^^^
2024-03-06 14:56:53.771
openneuro-prod-dataset-worker
    return func(*args, **kwds)
2024-03-06 14:56:53.769
openneuro-prod-dataset-worker
Traceback (most recent call last):   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run   File "/usr/local/lib/python3.11/site-packages/elasticapm/traces.py", line 1080, in decorated
2024-03-06 14:56:53.638
openneuro-prod-dataset-worker
error: failed to push some refs to 'ssh://github.com/OpenNeuroDatasets/ds003404.git'
2024-03-06 14:56:53.638
openneuro-prod-dataset-worker
 ! [remote rejected] 1.0.2 -> main (pre-receive hook declined)
2024-03-06 14:56:53.638
openneuro-prod-dataset-worker
To ssh://github.com/OpenNeuroDatasets/ds003404.git
2024-03-06 14:56:53.554
openneuro-prod-dataset-worker
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
2024-03-06 14:56:53.554
openneuro-prod-dataset-worker
remote: error: File sub-C34/func/sub-C34_task-rest_run-1_bold.nii.gz is 306.44 MB; this exceeds GitHub's file size limit of 100.00 MB        
2024-03-06 14:56:53.554
openneuro-prod-dataset-worker
remote: error: See https://gh.io/lfs for more information.        
2024-03-06 14:56:53.554
openneuro-prod-dataset-worker
remote: error: Trace: 03343a1bfa54152f885b23e59fe6527bbadf95d709d4c7358312954c12ae8b76    
```

</p>
</details> 

### Expected behavior

Needs fixing and I don't know how.

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
This looks like it was fixed.
