### ISSUE TITLE
Dataset ds005444 not saving uploads

### ISSUE THREAD

**Issue by bf777** [OpenNeuroOrg/openneuro#3134]
### Dataset issue

When trying to upload or update files in ds005444 (through the online GUI as well as the CLI), a large dataset of 369.5 GB, no files seem to be added to the online dataset in spite of the upload seemingly progressing. Every time I try to add files to the repository, it acts as though there's no remote files. The upload also hangs right before completion on the GUI progress bar. When attempting the upload in the command line interface, the following error appears:

```
Error [ServerError]: Response not successful: Received status code 502
    at Object.throwServerError (/arc/home/bforys/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/utils/utils.cjs:45:17)
    at parseJsonBody (/arc/home/bforys/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/http/http.cjs:275:15)
    at /arc/home/bforys/.nvm/versions/node/v20.17.0/lib/node_modules/@openneuro/cli/node_modules/@apollo/client/link/http/http.cjs:311:48
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://openneuro.org/crn/graphql',
      status: 502,
      statusText: 'Bad Gateway',
      headers: [Headers],
      counter: 0
    }
  },
  statusCode: 502,
  result: '\n' +
    '<html><head>\n' +
    '<meta http-equiv="content-type" content="text/html;charset=utf-8">\n' +
    '<title>502 Server Error</title>\n' +
    '</head>\n' +
    '<body text=#000000 bgcolor=#ffffff>\n' +
    '<h1>Error: Server Error</h1>\n' +
    '<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n' +
    '<h2></h2>\n' +
    '</body></html>\n'
}
```

The same result occurs when uploading from Mac or Linux, via Chrome, Firefox, or Safari. The BIDS validator runs successfully. This is linked to the Neurostars topic: [https://neurostars.org/t/openneuro-upload-stuck-near-end-directory-is-empty/30338](https://neurostars.org/t/openneuro-upload-stuck-near-end-directory-is-empty/30338) but I thought it would be helpful to post it here too.

### Command used:
Uploading via GUI, from a folder on a remote HPC cluster mounted on Ubuntu 22.04 via sshfs with full permissions.
Uploading via CLI directly from an HPC cluster running Rocky Linux 9, using the commands:
```
openneuro upload /arc/project/st-toddrebe-1/SENSIGEN/BIDS_dataset_aug25_24 --ignoreSubjectConsistency --ignoreWarnings
```

and then:

```
openneuro upload --dataset ds005441 /arc/project/st-toddrebe-1/SENSIGEN/BIDS_dataset_aug25_24 --ignoreSubjectConsistency --ignoreWarnings
```

Version:
- Browser upload (Firefox on Ubuntu 22.04)
- openneuro-cli v4.27.0

### The following datasets are affected

- [ ] ds005444

**Comment by bf777** [comment]
Just as an update: it seems that the upload is working for me via CLI in a new dataset (ds005449) so I have moved over to that dataset instead. However, even when uploading in smaller batches, this dataset appears to be intermittently skipping files (such that they are not visible on openneuro.org) but seems to still be registering them on the backend. For example, the number of participants listed in the dataset is larger than the number of participant folders that I can see, and when I re-upload README.md with changes, the BIDS validator on openneuro.org only (not the CLI) reports the following error:
```
A BIDS dataset MUST NOT contain more than one `README` file (with or without extension) at its root directory.
```

**Comment by bf777** [comment]
It appears that ds005449 has fully uploaded and I was able to publish it (it looks like the files that were stuck appeared after I made a small update to the dataset), so I will close this issue.
