### ISSUE TITLE
404: ds000221

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#3241]
### What went wrong?

https://openneuro.org/datasets/ds000221/ is 404'ing. I can login to worker 0 and see it in the directory.

### Expected behavior

Should show up.

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by nellh** [comment]
The related traceback:
```
ERROR:falcon:[FALCON] Unhandled exception in ASGI app
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/falcon/asgi/app.py", line 407, in __call__
    await responder(req, resp, **params)
  File "/srv/datalad_service/handlers/snapshots.py", line 26, in on_get
    files = get_tree(self.store, dataset, snapshot)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/datalad_service/tasks/files.py", line 38, in get_tree
    return get_repo_files(dataset, dataset_path, tree)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/datalad_service/common/annex.py", line 239, in get_repo_files
    files = get_repo_urls(dataset_path, files)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/datalad_service/common/annex.py", line 187, in get_repo_urls
    matchedRemote = parse_remote_line(line)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/datalad_service/common/annex.py", line 91, in parse_remote_line
    remoteConfig = dict(item.split('=')
                   ^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #6 has length 3; 2 is required
ERROR:root:Request failed without exception details
```
The frontend should also show 500 instead of 404 since this is an endpoint crash, not a missing dataset.

**Comment by nellh** [comment]
This is resolved.
