### ISSUE TITLE
SciTran authentication duplicate key for ORCID users

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#597]
This looks like the cause of some recent login issues - I've replaced the identifying key with 0000 below.

```
core_1    |   InsecurePlatformWarning
core_1    | 2018-04-25 18:41:54             root               webapp2.py  1552:ERRO 
core_1    | Traceback (most recent call last):
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1535, in __call__
core_1    |     rv = self.handle_exception(request, response, e)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1529, in __call__
core_1    |     rv = self.router.dispatch(request, response)
core_1    |   File "./api/api.py", line 156, in dispatcher
core_1    |     rv = router.default_dispatcher(request, response)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
core_1    |     return route.handler_adapter(request, response)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1101, in __call__
core_1    |     handler = self.handler(request, response)
core_1    |   File "./api/handlers/userhandler.py", line 17, in __init__
core_1    |     super(UserHandler, self).__init__(request, response)
core_1    |   File "./api/base.py", line 53, in __init__
core_1    |     identity = provider(access_token)
core_1    |   File "./api/auth/provider.py", line 51, in orcid
core_1    |     email = next(e.email_email.cdata for e in emails.email_email if e['primary'] == 'true')
core_1    | StopIteration
core_1    | [pid: 44|app: 0|req: 3038/24176] - () {56 vars in 1029 bytes} [Wed Apr 25 18:41:54 2018] GET /api/users/self => generated 228 bytes in 259 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
core_1    | 2018-04-25 18:41:54      scitran.api                  base.py    83:INFO drone "CRN Server" request accepted
core_1    | /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
core_1    |   InsecurePlatformWarning
core_1    | 2018-04-25 18:41:54             root               webapp2.py  1552:ERRO E11000 duplicate key error collection: scitran.users index: _id_ dup key: { : "0000" }
core_1    | Traceback (most recent call last):
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1535, in __call__
core_1    |     rv = self.handle_exception(request, response, e)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1529, in __call__
core_1    |     rv = self.router.dispatch(request, response)
core_1    |   File "./api/api.py", line 156, in dispatcher
core_1    |     rv = router.default_dispatcher(request, response)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
core_1    |     return route.handler_adapter(request, response)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1102, in __call__
core_1    |     return handler.dispatch()
core_1    |   File "./api/base.py", line 131, in dispatch
core_1    |     return super(RequestHandler, self).dispatch()
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 572, in dispatch
core_1    |     return self.handle_exception(e, self.app.debug)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
core_1    |     return method(*args, **kwargs)
core_1    |   File "./api/handlers/userhandler.py", line 92, in post
core_1    |     result = mongo_validator(permchecker(self.storage.exec_op))('POST', payload=payload)
core_1    |   File "./api/validators.py", line 89, in mongo_val
core_1    |     return exec_op(method, **kwargs)
core_1    |   File "./api/auth/userauth.py", line 26, in f
core_1    |     return exec_op(method, _id=_id, query=query, payload=payload, projection=projection)
core_1    |   File "./api/dao/containerstorage.py", line 40, in exec_op
core_1    |     return self._create_el(payload)
core_1    |   File "./api/dao/containerstorage.py", line 47, in _create_el
core_1    |     return self.dbc.insert_one(payload)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 625, in insert_one
core_1    |     bypass_doc_val=bypass_document_validation),
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 530, in _insert
core_1    |     check_keys, manipulate, write_concern, op_id, bypass_doc_val)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 513, in _insert_one
core_1    |     _check_write_command_response([(0, result)])
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 300, in _check_write_command_response
core_1    |     raise DuplicateKeyError(error.get("errmsg"), 11000, error)
core_1    | DuplicateKeyError: E11000 duplicate key error collection: scitran.users index: _id_ dup key: { : "0000" }
core_1    | [pid: 46|app: 0|req: 11854/24177] - () {42 vars in 551 bytes} [Wed Apr 25 18:41:54 2018] POST /api/users => generated 114 bytes in 151 msecs (HTTP/1.1 500) 2 headers in 100 bytes (1 switches on core 1)
core_1    | 2018-04-25 18:41:54      scitran.api                  base.py    83:INFO drone "CRN Server" request accepted
core_1    | 2018-04-25 18:41:54             root               webapp2.py  1552:ERRO E11000 duplicate key error collection: scitran.groups index: _id_ dup key: { : "0000" }
core_1    | Traceback (most recent call last):
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1535, in __call__
core_1    |     rv = self.handle_exception(request, response, e)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1529, in __call__
core_1    |     rv = self.router.dispatch(request, response)
core_1    |   File "./api/api.py", line 156, in dispatcher
core_1    |     rv = router.default_dispatcher(request, response)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
core_1    |     return route.handler_adapter(request, response)
core_1    |   File "/usr/local/lib/python2.7
python2.7/dist-packages/webapp2.py", line 1102, in __call__
core_1    |     return handler.dispatch()
core_1    |   File "./api/base.py", line 131, in dispatch
core_1    |     return super(RequestHandler, self).dispatch()
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 572, in dispatch
core_1    |     return self.handle_exception(e, self.app.debug)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
core_1    |     return method(*args, **kwargs)
core_1    |   File "./api/handlers/grouphandler.py", line 80, in post
core_1    |     result = permchecker(mongo_validator(self.storage.exec_op))('POST', payload=payload)
core_1    |   File "./api/auth/groupauth.py", line 20, in f
core_1    |     return exec_op(method, _id=_id, query=query, payload=payload, projection=projection)
core_1    |   File "./api/validators.py", line 89, in mongo_val
core_1    |     return exec_op(method, **kwargs)
core_1    |   File "./api/dao/containerstorage.py", line 40, in exec_op
core_1    |     return self._create_el(payload)
core_1    |   File "./api/dao/containerstorage.py", line 47, in _create_el
core_1    |     return self.dbc.insert_one(payload)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 625, in insert_one
core_1    |     bypass_doc_val=bypass_document_validation),
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 530, in _insert
core_1    |     check_keys, manipulate, write_concern, op_id, bypass_doc_val)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 513, in _insert_one
core_1    |     _check_write_command_response([(0, result)])
core_1    |   File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 300, in _check_write_command_response
core_1    |     raise DuplicateKeyError(error.get("errmsg"), 11000, error)
core_1    | DuplicateKeyError: E11000 duplicate key error collection: scitran.groups index: _id_ dup key: { : "0000" }
core_1    | [pid: 42|app: 0|req: 2073/24178] - () {42 vars in 551 bytes} [Wed Apr 25 18:41:54 2018] POST /api/groups => generated 114 bytes in 4 msecs (HTTP/1.1 500) 2 headers in 100 bytes (1 switches on core 0)
core_1    | 2018-04-25 18:41:54      scitran.api                  base.py    83:INFO drone "CRN Server" request accepted
core_1    | 2018-04-25 18:41:54      scitran.api                  base.py   177:WARN 404 Element not added in list roles of container groups 0000
core_1    | [pid: 44|app: 0|req: 3039/24179] - () {42 vars in 603 bytes} [Wed Apr 25 18:41:54 2018] POST /api/groups/0000/roles => generated 106 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 94 bytes (1 switches on core 1)
core_1    | /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
core_1    |   InsecurWmechanismarning
core_1    | 2018-04-25 18:41:54             root               webapp2.py  1552:ERRO 
core_1    | Traceback (most recent call last):
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1535, in __call__
core_1    |     rv = self.handle_exception(request, response, e)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1529, in __call__
core_1    |     rv = self.router.dispatch(request, response)
core_1    |   File "./api/api.py", line 156, in dispatcher
core_1    |     rv = router.default_dispatcher(request, response)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
core_1    |     return route.handler_adapter(request, response)
core_1    |   File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1101, in __call__
core_1    |     handler = self.handler(request, response)
core_1    |   File "./api/handlers/userhandler.py", line 17, in __init__
core_1    |     super(UserHandler, self).__init__(request, response)
core_1    |   File "./api/base.py", line 53, in __init__
core_1    |     identity = provider(access_token)
core_1    |   File "./api/auth/provider.py", line 51, in orcid
core_1    |     email = next(e.email_email.cdata for e in emails.email_email if e['primary'] == 'true')
core_1    | StopIteration
```

**Comment by nellh** [comment]
Confirmed this is due to having a public email but a private primary email. We should catch this error and show a warning like we do when a user has no public email on their ORCID profile.

**Comment by nellh** [comment]
@chrisfilo A fix for this is deployed. Going back through logs there's been a fair number of login failures due to this bug so hopefully this resolves the login issues for most ORCID users who were having trouble.

* ORCID users no longer need to make their primary email public, they just need at least one public email address on their profile.
* A user logging in with no public emails will get an error message asking them to set an email address to public.

**Comment by chrisgorgo** [comment]
Great! Thanks for getting to the bottom of this.

**Comment by chrisgorgo** [comment]
Can this be closed? I thought I saw on slack that a fix was deployed.

**Comment by nellh** [comment]
Yes, this was deployed. I saw there's still a user having issues but it must be unrelated to this fix, we can close this issue and keep investigating that in #534.
