### ISSUE TITLE
Error: socket hang up after uploads

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#604]
For the new backend, after upload something is still reading the closed socket. Does not seem to cause issues besides this error message.

```
server_1   | Error: socket hang up
server_1   |     at createHangUpError (_http_client.js:331:15)
server_1   |     at Socket.socketOnEnd (_http_client.js:423:23)
server_1   |     at emitNone (events.js:111:20)
server_1   |     at Socket.emit (events.js:208:7)
server_1   |     at endReadableNT (_stream_readable.js:1055:12)
server_1   |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
server_1   |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by nellh** [comment]
This can hang nginx - so need to track this down sooner than later.

**Comment by nellh** [comment]
This is a blocked read socket in the gunicorn worker and is fixed in https://github.com/OpenNeuroOrg/datalad-service/commit/b9f7188c39664fb21972c88c76cf7a1b89344f61.
