### ISSUE TITLE
Dataset upload silent failure on Node 10 and Windows

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#646]
Upload to dev using cli from npm.
```
filo@MSI MINGW64 ~
$ openneuro upload -i /d/data/7t_trt
? This will create a new dataset, continue? Yes
"ds001004" created with label "7t_trt"
Transferring "D:\data\7t_trt\.bidsignore" - 100% complete
Transferring "D:\data\7t_trt\dataset_description.json" - 100% complete
Transferring "D:\data\7t_trt\participants.tsv" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-fullbrain_bold.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-fullbrain_run-1_physio.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-fullbrain_run-2_physio.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-prefrontal_bold.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-prefrontal_physio.json" - 100% complete
Transferring "D:\data\7t_trt\sub-01\sub-01_sessions.tsv" - 100% complete
Transferring "D:\data\7t_trt\sub-01\ses-1\sub-01_ses-1_scans.tsv" - 100% complete
Transferring "D:\data\7t_trt\sub-01\ses-1\anat\sub-01_ses-1_inv-1_mp2rage.nii.gz" - 4% complete (20.5 MB remaining)

filo@MSI MINGW64 ~
$ ls -al /d/data/7t_trt
total 118
drwxr-xr-x 1 filo 197609    0 May  8 13:13 ./
drwxr-xr-x 1 filo 197609    0 May 22 14:14 ../
-rw-r--r-- 1 filo 197609   16 May  8 13:13 .bidsignore
-rw-r--r-- 1 filo 197609   55 Jan 11  2016 dataset_description.json
-rw-r--r-- 1 filo 197609  482 Jan 11  2016 participants.tsv
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-01/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-02/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-03/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-04/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-05/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-06/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-07/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-08/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-09/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-10/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-11/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-12/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-13/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-14/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-15/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-16/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-17/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-18/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-19/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-20/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-21/
drwxr-xr-x 1 filo 197609    0 May  6  2017 sub-22/
-rw-r--r-- 1 filo 197609 1293 Jan 11  2016 task-rest_acq-fullbrain_bold.json
-rw-r--r-- 1 filo 197609  113 Jan 11  2016 task-rest_acq-fullbrain_run-1_physio.json
```

Surprisingly the dataset was created: https://openneuro.dev.sqm.io/datasets/ds001004

**Comment by chrisgorgo** [comment]
Getting the same thing with another dataset (much smaller). Also partial upload - https://openneuro.dev.sqm.io/datasets/ds001003

```
filo@MSI MINGW64 ~
$ openneuro upload -i /d/data/ds000051_small2/
? This will create a new dataset, continue? Yes
"ds001003" created with label "ds000051_small2"
Transferring "D:\data\ds000051_small2\CHANGES" - 100% complete
Transferring "D:\data\ds000051_small2\dataset_description.json" - 100% complete
Transferring "D:\data\ds000051_small2\README" - 100% complete
Transferring "D:\data\ds000051_small2\task-abstractconcretejudgment_bold.json" - 100% complete
Transferring "D:\data\ds000051_small2\sub-01\anat\sub-01_run-01_inplaneT2.nii.gz" - 100% complete
Transferring "D:\data\ds000051_small2\sub-01\anat\sub-01_run-01_T1w.nii.gz" - 15% complete (3.9 MB remaining)
```
The transfer seems to be interrupted, but there are no errors.

**Comment by nellh** [comment]
server_1   | Error: write EPIPE
server_1   |     at _errnoException (util.js:1022:11)
server_1   |     at WriteWrap.afterWrite (net.js:867:14)

This looks like a client bug. What version of node are you using? Seems like a file stream is going away early if it's stopping part way through a file.

**Comment by chrisgorgo** [comment]
Just tried with latest master

```
$ yarn openneuro upload -i /d/data/7t_trt
yarn run v1.6.0
$ node packages/openneuro-cli/src upload -i D:/data/7t_trt
? This will create a new dataset, continue? Yes
"ds001005" created with label "7t_trt"
Transferring "D:\data\7t_trt\.bidsignore" - 100% complete
Transferring "D:\data\7t_trt\dataset_description.json" - 100% complete
Transferring "D:\data\7t_trt\participants.tsv" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-fullbrain_bold.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-fullbrain_run-1_physio.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-fullbrain_run-2_physio.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-prefrontal_bold.json" - 100% complete
Transferring "D:\data\7t_trt\task-rest_acq-prefrontal_physio.json" - 100% complete
Transferring "D:\data\7t_trt\sub-01\sub-01_sessions.tsv" - 100% complete
Transferring "D:\data\7t_trt\sub-01\ses-1\sub-01_ses-1_scans.tsv" - 100% complete
(node:6892) UnhandledPromiseRejectionWarning: Error: GraphQL error: write ECONNRESET
    at new ApolloError (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:121:28)
    at Object.next (D:\drive\workspace\openneuro\node_modules\apollo-client\bundle.umd.js:965:33)
    at notifySubscription (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:126:18)
    at onNotify (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:161:3)
    at SubscriptionObserver.next (D:\drive\workspace\openneuro\node_modules\apollo-link-context\node_modules\zen-observable\lib\Observable.js:215:7)
    at SubscriptionObserver.next (D:\drive\workspace\openneuro\node_modules\zen-observable\zen-observable.js:158:20)
    at D:\drive\workspace\openneuro\node_modules\apollo-upload-client\lib\main\index.js:149:24
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:6892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Transferring "D:\data\7t_trt\sub-01\ses-1\anat\sub-01_ses-1_inv-1_mp2rage.nii.gz" - 4% complete (20.5 MB remaining)
Done in 9.93s.
```

**Comment by chrisgorgo** [comment]
This user run into inability of running the CLI on Windows: https://openneuro.freshdesk.com/a/tickets/201

**Comment by nellh** [comment]
With the rewritten CLI uploader this should be fixed, we've dropped the library causing this.
