### ISSUE TITLE
SyntaxError (Unexpected token) running openneuro-cli

### ISSUE THREAD

**Issue by oesteban** [OpenNeuroOrg/openneuro#656]
Running Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

Node settings:
node-5.9.0
npm-3.7.3

Installed with npm (`npm -g install openneuro-cli`)

```
$ openneuro --help
/home/oesteban/.nvm/v5.9.0/lib/node_modules/openneuro-cli/node_modules/esm/esm.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";const{defineProperty:e}=Reflect,{freeze:t}=Object,{versions:r}=process,n=r.chakracore,o=r.v8||n,c=process.version,{filename:u,id:l}=module,a=l.startsWith("internal/")?N("internal/bootstrap/loaders"):void 0,{Script:i}=require("vm"),{runInNewContext:s,runInThisContext:d}=i.prototype,{existsSync:_,mkdirSync:f,readFileSync:p,unlinkSync:m,writeFileSync:h}=require("fs"),{sep:y}=require("path"),q=require("module"),b=a&&a.NativeModule,v=new q(l,null),x=module.constructor.length>1;let S;v.filename=u,v.parent=module.parent;let g=require;function D(){let e,t,r,u,l,a="esm.js";if(b)u=b._source["internal/esm/loader"];else{const n=w(c+"\0"+o)+".blob",i=__dirname+y+"esm"+y+"loader.js";l=__dirname+y+"node_modules",r=l+y+".cache",t=r+y+n,e=I(t),u=I(i,"utf8"),a=__dirname+y+a}const f=new i("(function (require, module, __shared__) { "+u+"\n});",{__proto__:null,cachedData:

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/oesteban/.nvm/v5.9.0/lib/node_modules/openneuro-cli/src/index.js:4:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

happens regardless you add an argument (`--help`), other arguments (e.g. `login`) or not.

**Comment by nellh** [comment]
@oesteban The minimum supported version of NodeJS is Node 8 (LTS). Please give that a try.

I'll add that to the package.json file so it warns you on install.

**Comment by nellh** [comment]
The change to require a supported node version will be in the next major release published to npm.
