### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/output/data/derivatives'

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#79]
https://openneuro.dev.sqm.io/datasets/ds000105/versions/00001?app=mindboggle&version=1&job=418a5959-43ec-459f-a614-2c41ad701f4e

```
^@Namespace(analysis_level='participant', bids_dir='/snapshot/data', output_dir='/output/data', participant_label=['13'])
['13']
running
subject_label is 13
/snapshot/data/13/anat/sub-13_T1w.nii.gz
/snapshot/data/13/anat/sub-13_ses-*_T1w.nii.gz
images are ['/snapshot/data/sub-13/anat/sub-13_T1w.nii.gz']
Create missing output directory /output/data/derivatives/mindboggle
Traceback (most recent call last):
  File "/opt/conda/bin/mindboggle123", line 122, in <module>
    os.makedirs(OUT)
  File "/opt/conda/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/output/data/derivatives'
Traceback (most recent call last):
  File "~/code/run.py", line 76, in <module>
    run_mindboggle(t1, label, args.output_dir)
  File "~/code/run.py", line 25, in run_mindboggle
    check_call(cmd)
  File "/opt/conda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mindboggle123', '/snapshot/data/sub-13/anat/sub-13_T1w.nii.gz', '--id', 'sub-13', '--out', '/output/data/derivatives/mindboggle', '--working', '/output/data/scratch']' returned non-zero exit status 1
```

This could be a problem with the app itself, but I don't see how... Creating this directory should be possible.

**Comment by nellh** [comment]
@chrisfilo BIDS-Apps/mindboggle#13 should fix this. Ran some tests with it locally and this allows it to write to volumes owned by any user.
