### ISSUE TITLE
FilStreamDisconnectUploadError causes server crash

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#808]
A similar error was fixed when uploads were canceled but looks like it's not fixed for every case. Might improve with #771 - the Apollo server 2.0 implementation includes some bug fixes for this.

```
server_1   | FileStreamDisconnectUploadError: Request disconnected during file upload stream parsing.
server_1   |     at IncomingMessage.request.on (/srv/node_modules/apollo-upload-server/lib/middleware.js:151:15)
server_1   |     at emitNone (events.js:106:13)
server_1   |     at IncomingMessage.emit (events.js:208:7)
server_1   |     at abortIncoming (_http_server.js:413:9)
server_1   |     at socketOnClose (_http_server.js:406:3)
server_1   |     at emitOne (events.js:121:20)
server_1   |     at Socket.emit (events.js:211:7)
server_1   |     at TCP._handle.close [as _onclose] (net.js:554:12)
```

**Comment by nellh** [comment]
This could be fixed by #771 - it has several bug fixes for the Upload scalar.
