### ISSUE TITLE
Unicode fields in auth token are not decoded correctly

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#833]
https://sentry.io/openneuro/openneuro/issues/636140705/

```
InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
  at parseJwt (./scripts/authentication/profile.js:10:28)
  at getProfile (./scripts/authentication/profile.js:19:24)
  at loginCheck (./scripts/authentication/loginCheck.js:5:19)
  at d (./scripts/authentication/logged-out.jsx:7:38)
  at None (./scripts/client.jsx:39:12)
...
(15 additional frame(s) were not displayed)
```

**Comment by nellh** [comment]
The parseJwt function we used here is not unicode safe.
