### ISSUE TITLE
Invalid JSON crashes inline viewer

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#836]
https://sentry.io/openneuro/openneuro/issues/637191092/

```
Error: Parser is unable to parse the response
  at apply (/srv/node_modules/superagent/lib/client.js:402:1)
  at emit (/srv/node_modules/component-emitter/index.js:133:1)
  at apply (/srv/node_modules/superagent/lib/client.js:705:1)
  at XMLHttpRequest.i (/srv/node_modules/raven-js/src/raven.js:375:1)
```

**Comment by nellh** [comment]
[This file](https://openneuro.org/datasets/ds001420/versions/00002/file-display/sub-01:ses-02:pet:sub-01_ses_02_pet.json) is not valid JSON. The JSON viewer should show an error and the raw content instead of crashing.

**Comment by nellh** [comment]
This is fixed at some point.
