### ISSUE TITLE
Papaya: RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#838]
https://sentry.io/openneuro/openneuro/issues/639116598/

```
RangeError: Offset is outside the bounds of the DataView
  at DataView.getUint8 (<anonymous>)
  at Object.b.isNIFTI1 (/papaya-831b0eb6.js:928:308)
  at Object.b.readHeader (/papaya-831b0eb6.js:930:172)
  at papaya.volume.nifti.HeaderNIFTI.readHeaderData (/papaya-831b0eb6.js:1303:313)
  at papaya.volume.Header.readHeaderData (/papaya-831b0eb6.js:1278:238)
...
(3 additional frame(s) were not displayed)
```

**Comment by nellh** [comment]
This is caused by [this file](https://openneuro.org/datasets/ds001378/versions/00003/results/openneuro.outputs%2Fd3c072b861f39f653a622855bb45eaad%2F387ca89a-1195-4fee-80dc-8f1157d94b74%2FmeanT1w.nii) which looks like output from a deleted job. Papaya crashes reading this file.

**Comment by nellh** [comment]
This is no longer an error we're seeing from Sentry.
