### ISSUE TITLE
openneuro-cli upload seems to finish successfully but produces error

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#851]
As far as I can tell, I was able to upload a dataset using the openneuro-cli tool successfully, since the dataset become available on openneuro.org and all the files seem to be there. But on the command line, I didn't receive a message saying it finished successfully. When I try to rerun, I get the following error:

> Skipping existing file - "derivatives/freesurfer/sub-16/ses-mri/anat/label/rh.aparc.DKTatlas40.annot"
Skipping existing file - "derivatives/freesurfer/sub-16/ses-mri/anat/label/rh.aparc.a2009s.annot"
Skipping existing file - "derivatives/freesurfer/sub-16/ses-mri/anat/label/rh.aparc.annot"
Transferring "derivatives/freesurfer/sub-01/ses-mri/anat/.DS_Store" - 100% complete
(node:32107) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:124:32)
    at Object.error (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1102:32)
    at notifySubscription (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:220:7)
    at notifySubscription (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:220:7)
    at /Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:156:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32107) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32107) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jbwexler** [comment]
I'm running into a similar issue while trying to update ds000201. This time all the files uploaded successfully but new files aren't available on openneuro. In fact, none of the snapshots are available now because the dataset is considered incomplete and gives me the option to resume upload. Here's the error given by openneuro-cli:

> Skipping existing file - "sub-9100/ses-2/func/sub-9100_ses-2_task-hands_bold.json"
Skipping existing file - "sub-9100/ses-2/func/sub-9100_ses-2_task-hands_bold.nii.gz"
Skipping existing file - "sub-9100/ses-2/func/sub-9100_ses-2_task-hands_events.tsv"
Skipping existing file - "sub-9100/ses-2/func/sub-9100_ses-2_task-hands_physio.tsv.gz"
(node:43275) UnhandledPromiseRejectionWarning: Error: GraphQL error: Internal Server Error
    at new ApolloError (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:124:32)
    at Object.next (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1076:37)
    at notifySubscription (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:126:18)
    at onNotify (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.next (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:215:7)
    at notifySubscription (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:126:18)
    at onNotify (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.next (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:215:7)
    at /Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:149:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:43275) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:43275) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nellh** [comment]
ds000201 is incomplete, it has uncommitted files. Are both of these errors from ds000201? The second error is an actual backend error and not a timeout.
