### ISSUE TITLE
Openneuro CLI uploading error.

### ISSUE THREAD

**Issue by egarza** [OpenNeuroOrg/openneuro#937]
Hi,

After I ran:

`openneuro upload --dataset datasetnumber -i datasetname`

The transfer went well, only updating files. 
However, then I got this error:

```
Transferring "sub-161/func/sub-161_task-rest_bold.json" - 100% complete 
(node:5181) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (/home/egarza/.config/yarn/global/node_modules/apollo-client/bundle.umd.js:85:32)
    at Object.error (/home/egarza/.config/yarn/global/node_modules/apollo-client/bundle.umd.js:916:32)
    at notifySubscription (/home/egarza/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/home/egarza/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/home/egarza/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:220:7)
    at notifySubscription (/home/egarza/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/home/egarza/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/home/egarza/.config/yarn/global/node_modules/zen-observable/lib/Observable.js:220:7)
    at linkFetch.then.then.then.catch.error (/home/egarza/.config/yarn/global/node_modules/apollo-upload-client/lib/main/index.js:130:24)
    at <anonymous>
(node:5181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems all files were sent and everything was fine in the end, so the error did not matter.

Kind regards

Eduardo

**Comment by nellh** [comment]
Hi, thanks for the report! This looks like a timeout, which means the backend may have finished the request but in longer than the maximum time. What dataset and version of openneuro-cli was this?

**Comment by egarza** [comment]
Hi,

Openneuro-cli version 2.2.0
Dataset: ds001514

**Comment by nellh** [comment]
Upgrading to 2.3.0 should resolve this for you. openneuro-cli 2.2.0 makes an extra request at the end of an upload that is no longer required by the 2.3.0 API.

There's a backlog issue to warn when using an incompatible version of openneuro-cli #886
