### ISSUE TITLE
TypeError: Cannot read property 'webkitRelativePath' of undefined

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#957]
https://sentry.io/openneuro/openneuro/issues/704197865/

```
TypeError: Cannot read property 'webkitRelativePath' of undefined
  at _editName (./scripts/uploader/uploader.jsx:203:56)
  at _addFiles (./scripts/uploader/uploader.jsx:250:51)
  at apply (./scripts/uploader/uploader.jsx:174:12)
...
(14 additional frame(s) were not displayed)
```

**Comment by chrisgorgo** [comment]
Triggered while using the web uploader.

**Comment by nellh** [comment]
If this is on resuming a dataset, #951 should fix it. Otherwise it looks like after validation this dataset does not include dataset_description.json
