### ISSUE TITLE
Error: Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#989]
I believe this is related to upload issues (as suggested by the full stack trace on sentry) and leads users to attempt to upload the dataset again instead of resuming.

https://sentry.io/openneuro/openneuro/issues/736182619/

```
Error: Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
  at ApolloError (../../src/errors/ApolloError.ts:56:5)
  at m (../../src/core/QueryManager.ts:290:13)
  at notifySubscription (/srv/node_modules/zen-observable/lib/Observable.js:134:16)
  at onNotify (/srv/node_modules/zen-observable/lib/Observable.js:165:3)
  at observer (/srv/node_modules/zen-observable/lib/Observable.js:224:7)
...
(1 additional frame(s) were not displayed)
```

**Comment by ckrountree** [comment]
Have not seen this issue since switching to the new hosting setup.
