### ISSUE TITLE
Validation of deleted dataset causes a server crash

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#99]
The validation endpoint crashes after not finding the files on disk.

**Comment by chrisgorgo** [comment]
We should probably handle this better in the validator itself. Could say a bit more about this case? What do you mean by "not finding files on disk"?

**Comment by nellh** [comment]
@chrisfilo Here's the validator error that was leading to the server crash:

```javascript
> const validator = require('./index.js')
undefined
> validator.BIDS('./does-not-exist', {}, () => {})
Error: ENOENT: no such file or directory, scandir './does-not-exist'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at getFiles (/home/nell/Git/crn/bids-validator/utils/files.js:191:20)
    at preprocessNode (/home/nell/Git/crn/bids-validator/utils/files.js:183:12)
    at callbackWrapper (/home/nell/Git/crn/bids-validator/utils/files.js:141:25)
    at getBIDSIgnore (/home/nell/Git/crn/bids-validator/utils/files.js:120:9)
    at Object.readDir (/home/nell/Git/crn/bids-validator/utils/files.js:151:5)
    at /home/nell/Git/crn/bids-validator/validators/bids.js:42:29
    at /home/nell/Git/crn/bids-validator/utils/options.js:20:17
    at /home/nell/Git/crn/bids-validator/utils/options.js:63:25
```

**Comment by chrisgorgo** [comment]
Thanks!
